### ISSUE TITLE
Search filters panel, toggle open/close rather than close after use

### ISSUE THREAD

**Issue by kenijo** [dnGrep/dnGrep#1]
Hi,

I couldn't find an other way to post my request.
I love this tools, you did a great job with it.
I would love though to have the options that are hidden behind the click on the funnel always visible a bit like on grepWin because I personally do a lot of searches while excluding so folders and that would make it easier to remember what I am not looking into and save a click.

Anyway, I hope this request makes it through. Keep up the good work and thank you so much for such a nice tool.

**Comment by doug24** [comment]
I have some ideas about changes to the top panel.  This proposal would address this issue #1, #179 (match/ignore patterns in the main UI), #221 (filter by date).  

In the default 'closed' state, the main window would look like this:
![image](https://cloud.githubusercontent.com/assets/17227248/24580932/726638ba-16c6-11e7-9d73-17b38e274923.png)

The 'search in' path is a normal drop-down, with the recent history of locations.  The match and ignore paths are always visible, and take 1/3 of the width of the screen.  The File Options would expand below these three inputs.  There is a summary of the hidden options next to the expander button.

When expanded, it would looks something like this:
![image](https://cloud.githubusercontent.com/assets/17227248/24580968/37846540-16c7-11e7-9fe3-1f48ae1bc36a.png)

With these changes, the normal height of the top section is one "row" larger.  The minimum width of the window would increase to 780 pixels allow horizontal space for the date controls, but I'm guessing no one probably uses it at minimum width.

**Comment by JVimes** [comment]
I like it! I often make the window narrow, though (~640px). What about using a WrapPanel directly inside the expander, and in it, put groups (Grids) of related controls? The date-time stuff would be a group, asterisk/regex, size, file system flags, etc.

**Comment by JVimes** [comment]
Thinking some more, if the aspect ratio varies much from group to group, there might be awkward space on the top/bottom of short groups within the WrapPanel. I more like the idea going with just three groups in the WrapPanel:
![image](https://cloud.githubusercontent.com/assets/6148201/24583596/2d38e340-170d-11e7-80c0-2cfa74cb715b.png)

**Comment by doug24** [comment]
That's a good suggestion.  When the window is wide, it looks as it did before.   I set the minimum width to 500 pixels, and it resizes to this.

![image](https://cloud.githubusercontent.com/assets/17227248/24584076/9d8a4712-1715-11e7-860d-d1b143efa4d5.png)

**Comment by kenijo** [comment]
I like it a lot too. that would definitely make me switch back to dnGREP as I use those settings a lot and hates having to open the dialog all the time. Maybe a setting option can be added for people who want it closed / opened by default.

The one comment I have would be to get rid of the "Options" folding line like this to save space:
![untitled](https://cloud.githubusercontent.com/assets/5394591/24584114/135931d2-1717-11e7-98b7-30f5e491cc7a.png)

Or add it as a column in the "File Options" to fill out the empty section JVimes mentioned.
Or just under the  "Encoding".
Those two would save a line as well.

**Comment by JVimes** [comment]
Looks great, Doug! And good suggestions, Kenijo. How's this plan sound:

- Let's combine "Options" and "File Options" into a single expander, and have its open/closed state persist so that users can leave it open (the current Options expander already persists).
- We fit the current Options checkboxes into the WrapPanel, probably below "Encoding".
- Let's make sure there is a 10px margin between the WrapPanel's sub-groups.

![image](https://cloud.githubusercontent.com/assets/6148201/24624006/ac20d36a-1867-11e7-8348-7d871e4b043a.png)

**Comment by kenijo** [comment]
Sounds perfect to me, it will simplify / clarify the UI.
Thank you.

**Comment by doug24** [comment]
I will give it a try, but I like having the options outside the collapsible area since I change some of them (Whole word & Case sensitive) a lot.  I change those more often than I change between regex and plain text (I pretty much never use xpath or phonetic), but I know everyone is different.  I have another layout idea that I'll give a try, too.

There is another issue, and that's the "Search in all files and subfolders" checkbox.  It is in the collapsible area, so it can be hidden from view.  Currently, checking that box both resets a number of options, but also disables them from change.  I don't like that the include/ignore paths fields can be disabled by a hidden checkbox.  I was thinking that it could be changed to a button - say "Reset Options" - that would reset the fields to 'search all' but leave everything enabled.  That is how I use it now - check and immediately uncheck it to reset, and leave everything enabled.

**Comment by doug24** [comment]
Included in 2.9.31 and later
