### ISSUE TITLE
Left panel with the list of files found: Is it possible to disable automatic vertical scrolling?

### ISSUE THREAD

**Issue by schittli** [dnGrep/dnGrep#1034]
Good morning,

**thank you very much sharing your great work!,** 
I use dnGrep a lot for my nonprofit work and it makes life better 😀 

Sometimes, dnGrep looks like this:
![image](https://github.com/dnGrep/dnGrep/assets/8282673/ee24315a-175b-4556-8db0-176845fbe68f)

Would it be possible to deactivate the horizontal scrollbar of the left panel (e.g. in the options) or to disable the automatic vertical scrolling?

The background is this:
* In the left panel, the most important information is the overview of files in which text has been found.
* However, if the scrollbar is moved, one gets a display that is probably useless to anyone.
* If one is interested in where exactly in the text something is found, one sees it in the right panel. 

Therefore, automatically moving the horizontal scrollbar in the left panel is probably only useful in rare cases. 

Thanks a lot, kind regards,
Thomas

**Comment by doug24** [comment]
I have to say I'm having a hard time understanding why you do not want the results list to scroll vertically to the current selection. Doesn't that just hide the 'most important information'?

I agree that the horizontal scrolling can be awkward when the match is not near the start of the line.  But I can't turn off horizontal scrolling and make it so no one can see the rest of the line.  There are users who do not use the preview window, and there are cases where you can only see results in the results tree and not in the preview window (large files, long lines, binary searches...). 

I could try to prevent the horizontal scrollbar from moving when the selected line changes - I suspect it is trying to scroll the match on that line into view, but I will have to investigate.  I think that would be the most expected behavior.

**Comment by doug24** [comment]
I think I see what you mean about no vertical scrolling - you want the selection to stay on the parent file node, not scroll through the child lines-with-matches nodes.  I can't do that - the select of the child line nodes is what drives the selection of lines in the preview window and a number of other things.

**Comment by doug24** [comment]
See the change in [release 4.1.27](https://github.com/dnGrep/dnGrep/releases/tag/v4.1.27.0)
