### ISSUE TITLE
Feature request:  Additional condition for dates - in the last ? minutes/hours/days, etc.

### ISSUE THREAD

**Issue by Tix2garr** [dnGrep/dnGrep#1037]
Currently there are options for "All dates", "Modified" and "Created" with From and To parameters, along with Past From and To for _hours_.  

Could you expand that a bit so that it isn't just past "hours", but include a dropdown with at least hours and days?

To be honest, if _I_ was going to do a modification, I would just go all out and do seconds, minutes, hours, days, weeks, months and years to make sure I didn't get another one of these annoying requests.  :-)

Just recently discovered dnGrep and really liking it!  Thank you!  :-)

Michael

**Comment by doug24** [comment]
Yes, I can add other options.  I think minutes is probably the smallest useful increment.

Using increments longer than hours makes me wonder what the user's intent is - especially since you can't see the actual time range that was used in the filter. 

I'm looking for options here:  should these time ranges just be multiples of the increment, or normalized to calendar time?

Examples:

0 to 1 days - is this the past 24 hours, or just today (midnight to current time)?
1 to 2 days - is this 24 hours starting 24 hours ago, or yesterday (midnight to midnight)?

0 to 1 months - is this the past 30 days, or the current month?
0 to 2 months - is this the past 60 days or the current month and last month?

0 to 1 years - is this the past 365 days, or the current year to date?
1 to 2 years - is this 365 days starting 365 days ago, or the last calendar year?

Should the number of months in the range reflect the number of days in each month within the range - normalized to the same date (and time?) the number months ago, or just always use 30 days?

**Comment by Tix2garr** [comment]
Wow...  I _really_ thought I had responded!  Sorry!  <wry smile>

For me, my "user's intent" is to find things I've done in the last X hours/days/months.  Minutes was just thrown in there as an example.  Restricting my search so I don't pull in a bunch of OTHER stuff that is older and not relevant to what I'm looking for.  :-)    I search for things in the last X days MUCH more than I use a date range.  Plus, an actual date range doesn't "adjust" when you run it later.  But that's just for ME.   

I would suggest keeping the From/to date ranges you have now and how they work.  Maybe just add a couple of options for "Not older than" and "Older than" like this:   (Could have hours/days/weeks/months/years...  <shrug>)
![image](https://github.com/dnGrep/dnGrep/assets/25388755/0842f56a-50f3-4366-b94e-0e0216bcfbab)

Some examples:     Will use 02/12/2024 03:00 PM as the **date/time of running the search**.
Not older than 1 day - Anything equal to or after 02/11/2024 00:00 AM
Older than 1 day - Anything before 02/11/2024 00:00 AM

Not older than 1 month - Anything equal to or after 01/12/24 00:00 AM
Older than 1 month - Anything before 01/12/24 00:00 AM
etc.

I honestly wouldn't worry about it past that.  Just do it like you are doing the date range now but with "Not older than" and "Older than" criteria.

And for hours, you are pretty much already doing that so...  :-)

Thanks for the awesome program!!  :-)

Michael

**Comment by doug24** [comment]
Thank-you for the input. I have been working on this for the February release.  I went with the simple time offsets - easier to implement and I think less confusing.  For example, setting 0 to 1 day will find all files modified between 24 hours ago and current time. No rounding for start of day, start of month, or things like that.

While I like your suggestion of the Older than and Not older than options, that doesn't give you a way to say something like between 1 and 2 months ago. 

The other two constraints I have is the dnGrep scripting and translations.  I want to minimize the changes on those and not break the existing script interface or existing scripts.

Here's what I have now:

<img src="https://github.com/dnGrep/dnGrep/assets/17227248/53c4a758-7dc9-43ed-b924-8ceaa147db1b" width="320"/>

**Comment by Tix2garr** [comment]
Heh...  Well as a programmer myself, I was figuring the to 00:00 would be more straightforward.  Of course, that also depends upon what language/functions you use.

"While I like your suggestion of the Older...."   Yup, you're right!  Your implementation is better.  :-)    Again, for _my_ use, I normally just go within the last 1 to however-many-days-ago-I-did-that-one-thing, but having the option for a slice in time is even better!

I _did_ think about the effect it would have on your scripting and was honestly afraid you wouldn't go for the changes I suggested.  BUT, you turned it around, kept the changes to your current specs minimal _**and**_ made it better than my suggestion!  :-D

I look forward to the February release.  :-)

Michael

**Comment by doug24** [comment]
Available in [release 4.1.27](https://github.com/dnGrep/dnGrep/releases/tag/v4.1.27.0)

**Comment by Tix2garr** [comment]
Lookin' good so far!  :-)

Since I'm a "newbie" to dnGrep, I'm still learnin' how awesome your program is.  

Thank you for your time, effort, _responsiveness_, and great program!!

Michael
