### ISSUE TITLE
dnGrep will not list any files with `.lib` extension.

### ISSUE THREAD

**Issue by fade2gray** [dnGrep/dnGrep#1068]
Version 4.1.27.0
Just discovered this.

**Comment by doug24** [comment]
You might be surprised that .lib files are actually archives.  In [v4.0.189](https://github.com/dnGrep/dnGrep/releases/tag/v4.0.189.0) (see release note), .lib was added to the list of default archive extensions because they were failing the test as binary files - they are binary but do not test positive as binary. 

Remove 'lib' from the list of archive extensions in the dnGrep Options, and you can search .lib files - but the 'Include binary files` filter on the main window does not work to exclude them.

**Comment by fade2gray** [comment]
Thanks for the heads-up.

**Comment by fade2gray** [comment]
@doug24 
Further to this, if the whole list of archive extensions are removed in settings, when returning to settings the list is found to have been reset, i.e. you can't save settings with an empty list, but replacing it with an asterisk works.
