### ISSUE TITLE
support more cmdline parameters

### ISSUE THREAD

**Issue by contest8** [dnGrep/dnGrep#1086]
Now dnGrep supports option on the Sort drop-down, enables natural sorting. It would be very nice having support cmdline parameters  for it.

**Comment by doug24** [comment]
I have been hoping to stop adding more command line options since I added scripting. With a script you have access to setting and calling all the UI features.

Can you give this a try and let me know if this works for you?  I know it's not as dynamic as just adding things to the command line, but I think most people calling dnGrep with command line parameters are doing it from their own script.

Create a script file in dnGrep, and save it.  Put everything you would want to set on the command line in the script. The script file must be in the Scripts directory.  You can create the script file outside of dnGrep once you understand the syntax.

Then start dnGrep like this:  `dnGrep -script _scriptname_`

You can include or exclude the .gsc file extension.  You can use `/sc` `-sc` or `-script` for the command line flag.  You should not include any other command line arguments when calling a script.

I just tried it now, and it looks like there is a bug saving/restoring the window layout when calling a script.  I will fix that for the next release.

**Comment by doug24** [comment]
[Help page for scripts](https://github.com/dnGrep/dnGrep/wiki/Scripting-Commands)

**Comment by doug24** [comment]
Fixed start with script bug in [v4.2.6](https://github.com/dnGrep/dnGrep/releases/tag/v4.2.6.0)
