### ISSUE TITLE
３个想法，不知能否做到。

### ISSUE THREAD

**Issue by zbb7001** [dnGrep/dnGrep#1090]
![image](https://github.com/dnGrep/dnGrep/assets/101622397/e8719592-d4f3-4196-aeef-f4e72d7fba24)
- 能否做到：如只需要搜索到５条，就自动暂停搜索。如果我需要进一步搜索，再点`继续`，进行更多的搜索。
- 能否增加搜索字体颜色设置，如果背景色也能设置就更好了。
- 能否在搜索结果上，可以任意复制，而不是现在的只能整段复制。

**Comment by doug24** [comment]
I will add the pause after 5 (configurable) results to the list of things to be done.  Just note that when dnGrep is running searches in parallel, it is not possible to stop at exactly 5.  When the fifth file is found, it will raise the pause event, but it is very likely that additional results will come in before all the threads pause.

The font color in the results list is already pure white unless it is read-only.  The background is #FFFF252525, which is pretty dark.  I don't think I will change the dark theme for this, but you can make your own theme with whatever colors you want - just start from an existing theme file - [see more here](https://github.com/dnGrep/dnGrep/wiki/Themes%2C-Language-and-Fonts).

What are you trying copy?  Just the file names?  Or any of the different Copy variations?  I'm reluctant to make a change here - if I make it copy only the selected items, then it becomes much more difficult to copy them all.  Doing a select all has bad side effects because the tree view is virtualized - meaning not all the data is rendered - but forces a render all when you do a select all.
