### ISSUE TITLE
dnGrep Crashed

### ISSUE THREAD

**Issue by atqooh** [dnGrep/dnGrep#1093]
When I searched for huge data the app got crashed and stop.
The CPU getting full

![image](https://github.com/dnGrep/dnGrep/assets/36100023/0b04965e-37d2-4087-b86f-a8bc2da9cb1a)

**Comment by doug24** [comment]
@atqooh  
How about giving me some information that I can use?
What is the file type?
How big is the file?
Anything unique about this file?
What are you searching for, and search parameters are you using?
What version of dnGrep are you using?

**Comment by atqooh** [comment]
> @atqooh How about giving me some information that I can use? What is the file type? How big is the file? Anything unique about this file? What are you searching for, and search parameters are you using? What version of dnGrep are you using?

Files type: Text - Documents - Photo - 7z
files size: 2 TB
Searching for: words like "manal53442@gmail.com"
dnGrep Version: 4.1.92.0

i face this .. 

![image](https://github.com/dnGrep/dnGrep/assets/36100023/92ce28d8-04c7-41e6-ba63-f8805f31892c)


and this ..

![image](https://github.com/dnGrep/dnGrep/assets/36100023/c7d46229-54d2-44f9-82aa-effdc9280fd4)


by the way,
when i use system got crashed ..
Can i let dnGrep use 70% or 80% from CPU?

**Comment by doug24** [comment]
This looks like the perfect storm of one inefficient process on top of another.

Unless it was specifically disabled when creating the archive, 7z archives are "solid" archives, the absolute worst format for searching; you can [read more here](https://github.com/dnGrep/dnGrep/wiki/Archive-Search).  The whole archive is extracted to access each file, over and over again.

And I am guessing that since you have all those Microsoft Word processes running that the archive contains old .doc files, not the newer .docx files.  The standard dnGrep plug-in to search old .doc files starts Word in the background, opens the document, and extracts the text using COM automation.  I have no idea about the 'AI Host for Microsoft Windows' - no doubt some new shiny object Microsoft has rushed to delivery and is starting for every Word process started. Yuck.

Suggestions:  

To reduce the CPU and memory use, uncheck "Search parallel" on the main window in the "More" filters collapsable section.  That will process one file at a time but will make the search take forever.  I doubt this is practical for your situation.

If you want to check if your archive is a solid archive, open it in 7zip and click the `Info` button on the toolbar.  If it is solid, there will be a `+` next solid, or a `-` if not.

<img src="https://github.com/dnGrep/dnGrep/assets/17227248/e27875b3-ae4f-426d-83c5-1a0af4d2d169" width="200"/>

To work around the problem with solid archives, extract the archive to a temp directory and search the extracted files. Or re-archive all the files in a non-solid format - zip or 7z non-solid. Doing this will pay for the effort many times over. 

If you have a lot of old .doc files to search, there is an alternative now to extract text from Word documents - you can try using [Apache Tika](https://github.com/dnGrep/dnGrep/discussions/1049) to extract text from the documents. Tika does not open the documents in Word like the existing plug-in but reads the binary format file directly.  The downside is having to launch a Java process for each document. I have only briefly tested this, so I don't know how it will compare for a large number of documents, but I think it will be an improvement.

**Comment by atqooh** [comment]
I had very huge of data (around 9 TB), all of them text files and some Doc inside folders and subfolders.
I need to compress them to decrease the size and i need to do my search in whole files even in subfolders. 

What is the best options?

Is .zip with high level option can help?

![image](https://github.com/dnGrep/dnGrep/assets/36100023/a151804a-46da-4786-87f2-86a65c1122b2)

**Comment by doug24** [comment]
Storing in 7z format with `Non-solid` will give better compression than zip.  Increasing the compression level (which increases dictionary size) will improve compression, but I don't know how that will affect the extraction for searching - but just disable solid.

<img src="https://github.com/dnGrep/dnGrep/assets/17227248/a73bf036-3b92-4521-8574-91595c1c7814" width="360"/>
