### ISSUE TITLE
[proposal] recursive statistics on file types in directory

### ISSUE THREAD

**Issue by Aliaksandr3by** [dnGrep/dnGrep#1099]
to get information about type of files and count ones.
something like this
![image](https://github.com/dnGrep/dnGrep/assets/11432724/1506da96-d5a1-4365-81f4-01c74d14f21d)

I have problems with being searched in *.mkv;*.flac;*.ogg; *.wav;*.mp4;*.dsf*.!qb;*.jpg;*.gif;*.png;*.jar;*.mogg....

https://unix.stackexchange.com/questions/18506/recursive-statistics-on-file-types-in-directory

![image](https://github.com/dnGrep/dnGrep/assets/11432724/4a5d17bb-f3a0-4ebc-901e-78aa70323948)

**Comment by doug24** [comment]
If I understand what you are asking - you want dnGrep to do count files by type, like you can do with the script?  That is pretty far away from what dnGrep does.

Is your problem with excluding those files types from the script?  I think the Find command allows you to exclude files by regular expression.

**Comment by Aliaksandr3by** [comment]
yes, you right.
I understand, 
I want it, that to add *.* extension to your program in the exclude pattern.
Some information about extension of files that in real dnGrep does not support is good for me.
I want to find out some information in folder that have mp3, mkv, log, txt, doc ....et cetera, and now I to stop program working, to add exclude of extension and start working.

![image](https://github.com/dnGrep/dnGrep/assets/11432724/5cfa5e6f-63ad-4129-98fa-4a070c2fd100)

if you think that it dont need, plz will close the issue ;

**Comment by doug24** [comment]
It seems easier (and more efficient) to list the file types you want to search instead of using *.* and a long list of exclusions.
All of these are binary files - why not just exclude all binary files?  Are there some binary file types do you want to include?
I also find it odd that you are searching in archives but trying to exclude jar files.  I think, but am not sure, that this would only exclude jar files that are inside another archive.  If you really don't want to search in jar files, you would have to remove 'jar' from the list of archive extension in the Options.

**Comment by Aliaksandr3by** [comment]
I am thinking that exclude pattern is excluding all *.jar, not exactly inside archive.
