### ISSUE TITLE
re-use the temp text in the cache to speed up

### ISSUE THREAD

**Issue by doug24** [dnGrep/dnGrep#1159]
### Discussed in https://github.com/dnGrep/dnGrep/discussions/1155

<div type='discussions-op-text'>

<sup>Originally posted by **ragebear00** July  6, 2024</sup>
Need to repeat searching a folder with 300K files. During the search, the target PDF/DOCX/EXCEL can be converted to text file in the temp folder.  

Can those temp text saved for future use?
-  if the PDF/DOCX/EXCEL temp text file is found and date of temp text file is later than the date of PDF/DOCX/EXCEL, OR 
- add MD5 at the file name. if the MD5 is the same
the  dnGREP will not convert again but re-use those temp text directly. 

The user can choose to keep temp text OR empty the temp text when exit dnGREP.  

It can increase speed dramatically.</div>

**Comment by doug24** [comment]
Added in [v4.2.59.0](https://github.com/dnGrep/dnGrep/releases/tag/v4.2.59.0)

**Comment by ragebear00** [comment]
thanks for great improvement. the immediately impact is the CPU load much lower if searching the same files. In the past, the CPU is 100% now is below 10% in my setting, since most files are stored in the NAS. The bandwidth is bottleneck now.  With 1000M bandwidth, searching 5000 PDF files drops from 22minutes to 5m with extra low CPU loading.

**Comment by ragebear00** [comment]
the hash of the large file over net may be improved by sampling portion of the file https://github.com/kalafut/imohash

**Comment by ragebear00** [comment]
the hash of the large file over net slows down the system. 
It may be improved by sampling portion of the file https://github.com/kalafut/imohash

**Comment by doug24** [comment]
How big of a file are you working with - what is the file size of a "large" file?

The project you reference here is written in Go, which I can't use. Same with the Python and Rust versions.  It has a good explanation of what it does, maybe I can implement something similar in .NET using the code examples.

**Comment by ragebear00** [comment]
The large files stop the system as below. 

for the files range 0K ~1000K
![image](https://github.com/user-attachments/assets/5f22bfe3-b00b-49b7-8ae5-0e9af7151113)

for the files range 1000K to 100,000K
![image](https://github.com/user-attachments/assets/f66c456d-eb7c-4733-a9e2-2e3156117761)

During the search WiFis fully loaded, cpu is 10%.
![image](https://github.com/user-attachments/assets/4ddc7fca-f3c2-4879-9904-34602928a49d)

A simpler solution maybe hash fix x% of the file, not fixed size (10% vs 1M). Assuming the new file will be different in size. The 10% of the file will be dramatically different. More discussion at 
https://superuser.com/questions/316840/md5sum-on-large-files

The percentage can be round(100K/fullsize)% at tail. So it reads app.100K but will vary if the full size varies. In other words, if the full size changes, the sampled data size will change. 

Of course, the solution above assumes that the hash will transport and read the file partially. If it still need to read the whole file over the net, the speed shall be the same.

**Comment by doug24** [comment]
Just to be clear, these statistics you show are for **after** the text has been extracted and saved locally as text files.  In this run, you are only hashing the files to lookup the file name of the previously extracted text in the cache.  And you have set your cache directory to the local disk, it's not cached on another network drive.

**Comment by ragebear00** [comment]
> Just to be clear, these statistics you show are for **after** the text has been extracted and saved locally as text files. 
[correct, and dnGREP closed and started again. If text files are not saved locally, the CPU will around 90%~100%.]

In this run, you are only hashing the files to lookup the file name of the previously extracted text in the cache. [correct, the same folder and same files and same search string after the first run and text extracted. In the first try, CPU load is much higher but the time needed is similar, since, I guess, both process the files are read fully and constrained by bandwidth. ]

And you have set your cache directory to the local disk, [correct]

it's not cached on another network drive. [correct]

**Comment by ragebear00** [comment]
In a nutshell, instead of hashing the whole file, hash the string (modified date + size) may improve the speed dramatically. 

spending more time on file comparison. Robocopy and FreeFileSync can review and compare thousands of files very quick. 

It  appears that Robocopy compare "size + modified date" only.
[https://superuser.com/questions/1114377/does-robocopy-skip-copying-existing-files-by-default#:~:text=In%20other%20words%3A%20Robocopy%20considers%20two%20files%20to,identical%20and%20therefore%20skips%20copying%20in%20that%20event.](url)

FileSync offers some options, the default is "size + modified date" 
[https://www.bing.com/ck/a?!&&p=2e2303eb28510d69JmltdHM9MTcyMzkzOTIwMCZpZ3VpZD0zOTYxZTkzZi0xNDcwLTY5ZDYtMjYwMy1mZGRmMTU1ZTY4ZmMmaW5zaWQ9NTQ4Nw&ptn=3&ver=2&hsh=3&fclid=3961e93f-1470-69d6-2603-fddf155e68fc&psq=filesync+how+to+decide+two+files+are+similar&u=a1aHR0cHM6Ly9mcmVlZmlsZXN5bmMub3JnL21hbnVhbC5waHA_dG9waWM9Y29tcGFyaXNvbi1zZXR0aW5ncyM6fjp0ZXh0PTElMjAxLiUyMENvbXBhcmUlMjBieSUyMEZpbGUlMjB0aW1lJTIwYW5kJTIwc2l6ZSwuJTIwLi4uJTIwMyUyMDMuJTIwQ29tcGFyZSUyMGJ5JTIwRmlsZSUyMHNpemU&ntb=1](url)

I check WinMerge it offers
- Full Contents (similar to hash the whole file)
- Quick Contents (similar to hash 10% of the file)
- Binary Contents
- Modified Date
- Modified Date and Size (similar to FileSync and Robocopy).
- Size


Overall, dnGrep may offer the similar options
- Full Contents (similar to hash the whole file, dnGREP offers now)
- Modified Date and Size (similar to FileSync and Robocopy) Instead of hash the whole file, Hash the string (modified date + size).

The new option may improve the speed dramatically.

**Comment by ragebear00** [comment]
if modified time is extracted for hash, it date/time may be standardized before hashing, since different setting in windows may generate different format and event different numbers for different timezone. 

Standardizing the date/time can allow the cache shared between different computers. 

Of course, without standardizing the date/time, the new string hash option can still optimize the search in the same computer, but cache sharing may not work.

**Comment by doug24** [comment]
I am working on it and will give you a couple of options.  The ImoHash you referenced above always includes the file size.  For these binary files consumed by the dnGrep plugins, it is pretty difficult to modify the file and not change the file size.

**Comment by ragebear00** [comment]
_For these binary files consumed by the dnGrep plugins, it is pretty difficult to modify the file and not change the file size._

how about to keep the file size and modified time with cached file?

current cache file (name + hash of the filesize)
2015.03.16_xxx.msg_B356FB38460B483CC63D3F8AE04D8838A8F7EF2F126284769E3D23F8256C1FF6

new cache file (name + string (filesize + modified date time))
2015.03.16_xxx.msg_12456879_2015031612235633 
12456879 is the size
2015031612235633  is the date + time.

**Comment by doug24** [comment]
Fixed in [4.2.84](https://github.com/dnGrep/dnGrep/releases/tag/v4.2.84.0)

**Comment by ragebear00** [comment]
Amazing!!!! complete 20K document search in 60 second. If Regex or Boolean, complete 5000 documents search
