### ISSUE TITLE
dnGrep crashes on startup with error: "Something broke in dnGrep"

### ISSUE THREAD

**Issue by reneignacio** [dnGrep/dnGrep#1177]
When I try to open dnGrep, I immediately get an error message that says, "Something broke in dnGrep. Check the error log for more details." The log path is indicated as C:\Users\User\AppData\Roaming\dnGREP\logs.

I have tried uninstalling and reinstalling the application, but the issue persists. I also attempted the following steps with no success:

Running dnGrep as Administrator.
Deleting the AppData\Roaming\dnGREP folder before reinstalling.
Ensuring no other instances of dnGrep are running.
The installation was done via Chocolatey, and it reports as successful. However, when I attempt to use the application, I encounter the following error:
![image](https://github.com/user-attachments/assets/bd3b41f1-8c13-4d18-a23d-a9deecb7ac50)
It seems there are issues with the WSL installation.

**Comment by doug24** [comment]
What version of dnGrep are you running?
What version were you upgrading from?

You show the path to the log file - can you show what error is in the log file when you get the error at startup, not the search error? Usually when you get an immediate error at startup, it has something to do with invalid data the dnGREP.Settings.dat file. dnGREP.Settings.dat is in C:\Users\User\AppData\Roaming\.  Exit dnGrep, rename or delete that file, and restart dnGrep.  Did it start without errors this time?

The error message you show is unrelated to the startup error.  dnGrep has nothing to do with WSL, other than you are searching an archive in wsl mounted as an UNC path.  This error is that 7zip cannot open the gz file because it is invalid.

**Comment by doug24** [comment]
@reneignacio I assume you have this working now. If not and you have more information, you can reopen this issue.
