### ISSUE TITLE
Search in Word documents results in numerous Word processes I have to kill, and a warning from Windows.

### ISSUE THREAD

**Issue by eirens-axiomint** [dnGrep/dnGrep#1189]
dnGrep 4.2.59.0
Installed today via .msi using this link: https://github.com/dnGrep/dnGrep/releases/download/v4.2.59.0/dnGREP.4.2.59.x64.msi
Windows 11

I did a search:
![P1 -- 2024-09-06, 17_43_49 -- ABC in _c__docs_ – dnGrep](https://github.com/user-attachments/assets/2affcf50-0ee5-4f33-b2ea-390945a8a1ce)

I tried to cancel it with {Cancel} button mid-search. That did nothing visible. {Pause} seemed to pause it though.

I got many of these:
![P1 -- 2024-09-06, 17_29_54 -- Microsoft Word Security Notice](https://github.com/user-attachments/assets/fe730d19-9a88-408c-8a44-7d3bae4b796b)

Transcript:

> Microsoft has blocked macros from running because the source of this file is untrusted.
> File Path: C:\Users\<myusername>\AppData\Local\Microsoft\Windows\INetCache\Content.Word\~WRC2931.tmp

Microsoft has blocked macros from running because the source of this file is untrusted.
"More information" link pointing here: https://support.microsoft.com/en-us/topic/a-potentially-dangerous-macro-has-been-blocked-0952faa0-37e7-4316-b61d-5b5ed6024216
{Disable Macros}

I did **not** press the {Disable Macros} button. Ever.

The directory mentioned in that message is full of .tmp files:

> Directory of C:\Users\<myusername>\AppData\Local\Microsoft\Windows\INetCache\Content.Word
> 
> 06 Sep 24  05:39 PM            16,384 ~WRF{084E2784-439B-4173-A547-E131DA07386D}.tmp
> 06 Sep 24  05:39 PM            16,384 ~WRF{0C96D9E9-6912-449D-A405-AD0B9F21ADE0}.tmp
> 06 Sep 24  05:39 PM             1,024 ~WRS{04F268D8-D690-4D75-9C38-9A2FEAB2EE67}.tmp
> 06 Sep 24  05:39 PM             1,024 ~WRS{0F0D7B48-6E7F-4017-B62F-C21AF0B576D3}.tmp
> 06 Sep 24  05:39 PM             1,024 ~WRS{15DC3F79-A0F4-4FE1-A675-12DC676DB941}.tmp
> 06 Sep 24  05:39 PM             1,024 ~WRS{16EDA3C5-BEC2-4FB8-B304-9A0ADB6A01A6}.tmp
> 06 Sep 24  05:39 PM             1,024 ~WRS{1D658C50-65E4-4999-911E-AE1891F4B967}.tmp
> 06 Sep 24  05:39 PM             1,024 ~WRS{22752E24-8BCB-4DAC-AF99-712E585A623A}.tmp
> 06 Sep 24  05:39 PM             1,024 ~WRS{283DE6DD-5D55-49F6-B168-4BF7C0F605BE}.tmp
> 06 Sep 24  05:39 PM             1,024 ~WRS{2A306004-347C-48F6-BA58-A142F7B29BBA}.tmp
> 06 Sep 24  05:39 PM             1,024 ~WRS{2ABE6E94-51C1-47B6-96EF-B3603C31FA42}.tmp
> 06 Sep 24  05:39 PM             3,702 ~WRS{2F625CF0-121D-4EA3-B276-013B986DF169}.tmp
> 06 Sep 24  05:39 PM             1,024 ~WRS{3050CDC8-F345-4826-BA69-C0502BD04EA0}.tmp
> 06 Sep 24  05:39 PM             1,024 ~WRS{37E6FE2D-54DC-4B02-8A65-D03C4916645B}.tmp
> 06 Sep 24  05:39 PM             1,024 ~WRS{3F1FE4B1-3A0D-45C6-9DE3-DEDE0AABCC0B}.tmp
> 06 Sep 24  05:39 PM             1,024 ~WRS{448449B6-4243-4D8A-B31F-C8300B13035D}.tmp
> 06 Sep 24  05:39 PM             1,024 ~WRS{53527969-789B-426F-823E-C44DD53672A9}.tmp

Task Manager is telling me about tons of "Microsoft Word" processes:
![P1 -- 2024-09-06, 17_40_26 -- Task Manager](https://github.com/user-attachments/assets/cacc7023-bc4a-420c-b2b8-e6370ba9785b)

This feels bad.

After exiting dnGrep and manually killing all those Word processes, a few more appear in Task Manager after a bit.

**Comment by doug24** [comment]
dnGrep can only search plain text files, so when it encounters a recognized binary file type, it calls a plug-in to extract plain text from the document, and then searches the extracted plain text.

One of the plug-ins is for old-style Word .doc files.  There are other plug-ins for the newer MS Office docx, xlsx, pptx, Open Documents odf, odt and for PDF files.

The Word plugin uses interop to open the document in Word, with visibility set to false.  So yes, if you are searching many .doc files, you will see many instances of Word run. dnGrep is telling Word to exit after the text is extracted, and Word does exit on my machine (Windows 11).  dnGrep is telling Word to disable all macros when opening the document (fixed in issue #539 back in September 2021), and that doesn't look like it is working your either. Those temp files are created by Word, not by dnGrep. Interop is ugly and the calling application has very little control over what happens, so I don't know why it is not working on your machine.

There is an alternative to the Word plug-in, and that is to use Apache Tika.  You will need to install Tika and create a plug-in configuration.  The instructions are here [Using Apache Tika with dnGrep](https://github.com/dnGrep/dnGrep/discussions/1049).  Tika extracts text from .doc files without using Word. 

Make sure to disable the Word plug-in in the dnGrep options dialog and add the `doc` extension to the list of extensions that Tika should handle.

If you are doing many files, then running Tika Server is more efficient, but does require you to start Tika Server separately - see the comment by ragebear00 on the dnGrep Tika page.

dnGrep v4.2.59.0 can cache the extracted text files, which greatly speeds up repeated searches of the same documents. The plug-is does not have to go back to the external application or library for each search. You can enable or disable the plug-in cache in the dnGrep Options.
