### ISSUE TITLE
提供优化建议

### ISSUE THREAD

**Issue by xxxdo1** [dnGrep/dnGrep#1214]
这个程序可以优化一下启动速度吗, 启动好慢啊, 每次都得等待 2-3s

预览文件查看器, 可以做成插件, 像 Total Commander 那样, 这个查看器不如TC的lister好用啊, 最好能让用户设置外部查看器

**Comment by doug24** [comment]
I did some checking on this, and I don't think there is much if any room for improvement.  

I added some instrumentation to the startup and collected data using PerfView.exe. The time from launching the exe to the main window finishing rendering is about 1.75 seconds.  

My machine:  Intel(R) Core(TM) i7-1185G7 @ 3.00GHz, x64, 16.0 GB RAM, Intel Iris XE Graphics, Windows 11 Home 23H2.

It takes about 0.25 seconds from when the starting the exe to the first user code in the app.  The startup must initialize the logging, process the command line, read the settings file, load the translation resource, load the app theme, load the plugins, and load the main window. I can't remove or move any of those things. The only expensive operation is loading the main window. It takes about 1 second to load the controls, bind controls to data, and position the window. I know this because replacing the main window with a blank window saves about 1 second of the startup time.  The app is WPF and I don't know any way around this. Changing from WPF is not an option.

During startup, about 70% of the cpu is on the main thread, and 30% is on other .NET tasks such as the JIT compiler.  The app already is precompiled at build time ([ReadyToRun](https://learn.microsoft.com/en-us/dotnet/core/deploying/ready-to-run)) to improve startup time by generating some native code in ahead-of-time compilation.

So, unless someone has a specific recommendation, I am not going to spend any more time on it.

**Comment by xxxdo1** [comment]
每次程序启动都会加载路径上存在的全部的资源, 翻译文件, 主题文件, 插件文件,这也是降低启动速度的因素, 可以改成只加载已设置的资源, 翻译, 主题, 插件等,  未设置的则不加载.

**Comment by doug24** [comment]
Maybe I wasn't clear, I've already looked at these things, they are just down in the noise.
Load settings: 18 ms
Themes: 114 ms
Plugins 7 ms

If you remove all the theme files from the external directory leaving only Dark and Light (the built-in themes), then loading the themes goes down to 75 ms.  So, if you want to save 40 ms, go ahead and delete the theme files.

The language resources are loaded by .NET, not by application code (the app just selects the active resource).  I deleted all the language resources except for English, and it didn't make any difference in the startup time.

There isn't anything I can see in the application code that will significantly impact the startup time, and really, I think it is fast enough as-is and there is no reason to spend hours optimizing milliseconds.
