### ISSUE TITLE
Integration with Everything

### ISSUE THREAD

**Issue by rzw** [dnGrep/dnGrep#1220]
dnGrep naturally cannot find a portable version of Everything by itself. There doesn't seem to be a possibility to enter the path of a portable installation of Everything. If I'm right this would be a feature request. If I'm wrong I'd appreciate some advice.

Thanks and best regards,
Rudy

**Comment by doug24** [comment]
I have not tested the integration a portable version of Everything.

What version of Everything are you using? There was a recent question about using 1.5 Alpha, and it turns out that the Everything API is missing in 1.5 Alpha, and you still need 1.4.1 running to support the Everything API.

dnGrep doesn't have any code to locate Everything.  dnGrep ships with the Everything SDK (Everything.dll), and the code to locate Everything is in that dll.  I could be wrong, but I think it is connecting to a running process/service, not to any actual disk location.

**Comment by rzw** [comment]
You are right regarding connection to running process rather than location. On a regular basis (and until now) I also used Everthing Version 1.5.0.1383a (x64). But since I use the portable version(s) I have both stable and alpha. Version 1.4.1 provides the option "Everything" alongside with "regular expression" and "wildcard". I will experiment and play with "Everything".

Thanks for your quick response. "Problem" solved!
