### ISSUE TITLE
Missing drag & drop found results .pdf file to external program; No double click possible

### ISSUE THREAD

**Issue by pstein** [dnGrep/dnGrep#1232]
I performed a search for a keyword in a partition full of pdf files.
dnGrep found some pdf file matches.

As I found out I cannot drag & drop the found result PDFs onto an external opened program (here: PDF editor).

Do I have to activate something for this action?

When I right click on a result line and select sub menu "Open with" then the sub sub menu is empty (even not a sub sub menu "select program" can be found).

And when I double click on a result pdf file then this cannot be opened by the default viewer.

All 3 actions are possible from File Explorer.

So this is at least a missing feature in dnGrep or even a bug.

Whats wrong?

**Comment by doug24** [comment]
> As I found out I cannot drag & drop the found result PDFs onto an external opened program (here: PDF editor).

This works for other programs - dropping text files onto Notepad/Notepad++, VS Code, Visual Studio, etc., and PDF files onto Sumatra PDF, and docx files onto Word.  I have not used PDF Editor, and I have no way of knowing what it expects to receive and what would be different.

> When I right click on a result line and select sub menu "Open with" then the sub sub menu is empty (even not a sub sub menu "select program" can be found).

The "Open with" submenu is populated with applications that you [configure](https://github.com/dnGrep/dnGrep/wiki/Custom-Editor-Integration). It sounds like you have not configured any. In the Options dialog, find the "Custom editor" section, and click the Add button. You can add any number of custom editors.  Some are preconfigured (choose from the drop down at the bottom of the Add dialog or configure your own selections.

> And when I double click on a result pdf file then this cannot be opened by the default viewer.

- Double click on a file node expands the node.
- Double click on a child line opens in the custom editor if configured, otherwise the associated application.
- Alt+double click on either a file node or child line opens in the associated application.
- Middle mouse button click on either a file node or a child line opens in the custom editor if configured and the associated application otherwise.

I think everything is working as expected.

**Comment by pstein** [comment]
@doug24:
Ok, I have configured "Open with" according to your hint.
It works now. Thank you

I can confirm that outwards drag & drop works for all other targets except my pdf editor.
Curios. However since I can Open With now its not that urgent any more

Regarding the double click:
Having to press ALT + Double click to open it in default application is not intuitive.
I hate to remember another hotkey beside my 234525 other hotkey combinations.

How can I tell dnGrep to open (a pdf) file in its default application when I simply double click on the files name (WITHOUT additionally pressing ALT)?

**Comment by doug24** [comment]
I think for most people, the expected behavior when double clicking the text on a tree node with children is to open the node if is closed and close it if is open. Yes, you can also click the tiny arrow, but it's must easier to hit the big target, not the little one. If I changed that behavior, I'm sure I would get an immediate issue to change it back, much like it happened when Visual Studio made a change like this.

But rather than just opening the file at the beginning, wouldn't you rather open it to the location when the search found a match?  That's what happens when you open the file node and double click on a line with a match. Your configured custom editor gets opened to the line and column of the match.  PDF files don't have lines and columns as text files, but with PDF files you can specify the page to open in the file, assuming your PDF application supports a 'page' command line argument. I searched for command line arguments for PDF Editor and couldn't find any documentation, but 'page' is supported by other PDF applications.  See the preconfigured options for Acrobat and Sumatra PDF in the Options dialog.
