### ISSUE TITLE
no supports for gb2312/utf8 encoding?

### ISSUE THREAD

**Issue by JVimes** [dnGrep/dnGrep#180]
_From [mfm...@sina.com](https://code.google.com/u/107484051280825188802/) on February 25, 2013 23:15:51_

it turns out to be no supports for greping gb2312/utf8 encoded text.
1. dngrep did find the occurs, but linenos and positions of the result are very wrong
2. chinese characters displayed in result pane are unreadable, while they are good in preview pane.
3. converting gb2312/utf8 encoded text file to unicode encoding will solve this problem, but it is a tough work and not feasible
3. env: dngrep version 2.7.1, win7 x64(simplified chinese)

_Original issue: http://code.google.com/p/dngrep/issues/detail?id=177_

**Comment by doug24** [comment]
This should be fixed in the 2.9.21 beta release, if anyone can test it.  The auto detect appears to work well if they files have encoding marks.  Otherwise, you can use the encoding selector, and that selection will be used when searching, replacing, in the results screen and in the preview.  The encoding selection is preserved when dnGrep is closed and reopened.

**Comment by JVimes** [comment]
Anyone have example files of GB2312 handy? I'd like to test this, and take a crack at unit tests.

**Comment by JVimes** [comment]
I found some Chinese text to try ([gb2312.txt](https://github.com/dnGrep/dnGrep/files/895144/gb2312.txt)), and seems to work fine if I pick the encoding in the drop-down.
