### ISSUE TITLE
"Archive Plugin" Search Ignored Patchs

### ISSUE THREAD

**Issue by JVimes** [dnGrep/dnGrep#188]
_From [pedrov...@gmail.com](https://code.google.com/u/109309281595840173147/) on May 10, 2013 14:31:47_

*What steps will reproduce the problem?*

1. "Archive Plugin" installed.
2. Patchs that match: _.7z,_.txt
3. Patchs to ignore: *.obj

*What is the expected output? What do you see instead?*

I expected a list that match only TXT files contained within 7Z, but includes OBJ contained within the same 7Z (NOT WISH THAT).

*What version of the product are you using? On what operating system?*

dnGREP 2.6.3 (Win7 32 bits)

*Please provide any additional information below.*

Thanks for attention.

_Original issue: http://code.google.com/p/dngrep/issues/detail?id=185_

**Comment by doug24** [comment]
I am working on this.

**Comment by doug24** [comment]
Changes for this issue are in 2.9.42 beta.  A couple of notes:
If you have only archive file extensions in the 'Paths that match' box, dnGrep will search all files inside the archives.  
If you include other types in the 'Paths that match' box, such as "*.zip;*.txt", dnGrep will search only .txt files inside the archive.  This does mean, however, that dnGrep will also search .txt files outside of the archives if the search path is a folder.
You can also exclude selected file types inside archives by using the 'Paths to ignore' box.  
If you include an archive file extension in the 'Paths that match', dnGrep will search the archives even if 'Include binary files' is not checked.

**Comment by JVimes** [comment]
@doug24 I think the behavior is pretty confusing. I vote we add a "include archives" checkbox below "include binary files". Then treat archives just like folders. I'm guessing plugins don't have UI access, and it's not worth implementing right now, so I'd do a hack: add a checkbox that only shows up if the archive plugin is installed. Let me know what you think. I'll add a new issue for it unless you're motivated to include it now. Thanks again!

**Comment by doug24** [comment]
Yes, that's a good idea.  I'll have a look at what impact that will have on things.  

The one thing I don't like about the archive support is that the current implementation uses 7zip to unzip all the archives into a temp folder.  It would be nice to read the files directly from the archive rather than going through the unzip.   If the performance is good, maybe the main app could support a few archive file formats using managed libraries without unzipping.  I don't know of any managed implementations that support the range of file formats that 7zip does, however, so the plugin will still be needed.

**Comment by JVimes** [comment]
I like that idea. I captured the "include archives checkbox" idea in #273, so I'll close this issue.
