### ISSUE TITLE
Comma seperated file extensions not searched

### ISSUE THREAD

**Issue by JVimes** [dnGrep/dnGrep#208]
_From [bcole...@cfnva.com](https://code.google.com/u/112689192746716288085/) on February 21, 2014 23:01:32_

What steps will reproduce the problem? 1. Search in / select filter / enter *.c, *.h, *.mcc
2. Asterisk pattern selected
3. Search only looks in *.c files
4. Same if set file filter to be *.{ch}; *.mcc
5. Search only looks in *.c or *.h files. What is the expected output? What do you see instead? Search should look in all the files whose pattern is entered after the comma or semicolon. What version of the product are you using? On what operating system? 2.7.2.0 on Win7 x64 Please provide any additional information below. Did I mention how awesome it is to have a worthy "grep" like tool for use in windows?

_Original issue: http://code.google.com/p/dngrep/issues/detail?id=205_

**Comment by doug24** [comment]
This turned out to be a problem with having whitespace between the comma and the next element in the list.  Should be fixed in 2.9.24 beta.  It will handle either comma or semi colon separated lists, and should also handle a filter or path with a comma embedded in the string - where it is not a separator.

**Comment by JVimes** [comment]
Verified fixed.
