### ISSUE TITLE
filter by date

### ISSUE THREAD

**Issue by az0** [dnGrep/dnGrep#221]
To reduce search time (by reducing disk I/O) and to reduce clutter in the list, please add a date filter like "modified between X to Y days ago."

As part of this, probably should add filtering based on create, write, and access times, as well as [FileAttributes](https://msdn.microsoft.com/en-us/library/system.io.fileattributes%28v=vs.110%29.aspx).

**Comment by doug24** [comment]
I've been working on this along with the changes to the layout #1.  If anyone has an opinion on this changes, it would be great to hear them now.  Here are the modes I'm thinking of putting in - do these work, or what would you prefer to see?

Case 1: all dates:
![image](https://cloud.githubusercontent.com/assets/17227248/24891140/b9497d0a-1e28-11e7-859e-24bf37345039.png)

Case 2: using file last modified time, include only files before a date:
![image](https://cloud.githubusercontent.com/assets/17227248/24891171/ed0fc86a-1e28-11e7-9d01-1d7dbd92b3d3.png)

Case 3: using the file last modified time, include only files after a date:
![image](https://cloud.githubusercontent.com/assets/17227248/24891194/1e8815dc-1e29-11e7-8b4f-24e95fe4fff2.png)

Case 4: using the file modified time, include only files in the specified date range:
![image](https://cloud.githubusercontent.com/assets/17227248/24891231/55ca3200-1e29-11e7-9615-a8c6b75bf1f7.png)

Case 5, using the file modified time, include only files modified in the past 8 hours:
![image](https://cloud.githubusercontent.com/assets/17227248/24891295/b8abf020-1e29-11e7-8393-24ccb6710b67.png)

Case 6, same as 5, but do not include files in the past hour:
![image](https://cloud.githubusercontent.com/assets/17227248/24891314/e50f984c-1e29-11e7-92b7-844504cd262a.png)

For each of these cases, you can use the file create time instead of last modified time.
![image](https://cloud.githubusercontent.com/assets/17227248/24891348/1ff635ce-1e2a-11e7-8268-eb77f0483f16.png)

A couple of notes:
- The date selectors allow only dates, not dates and times.  (I haven't found a date-time selector that I like, if anyone knows of a good wpf date-time selector, let me know).  If you want hour level resolution, you would have to use the hour range option.
 - The Before date cannot be earlier than the the After date, so you cannot do 'before date x OR after date y'.
 - There is just one date filter, so you can't have a filter on both Create and Modified times in one search operation.

**Comment by az0** [comment]
What you have shown here looks great! I am looking forward to it.

**Comment by JVimes** [comment]
I like it. How about saying "From/To", instead of "Date is After/Before"?

**Comment by doug24** [comment]
Included in 2.9.28
