### ISSUE TITLE
Results window text colour and font size customisation

### ISSUE THREAD

**Issue by TimChippingtonDerrick** [dnGrep/dnGrep#226]
Really like this tool, but sometimes have problems reading the text in the results window on hi-res screens or older low-quality screens. Can we have some customisation options for the font size and/or colour in the results screen?

**Comment by JVimes** [comment]
Thanks for pointing that out. I haven't tried dnGrep on a high-DPI display yet. I know [a lot](http://www.hanselman.com/blog/LivingAHighDPIDesktopLifestyleCanBePainful.aspx) of programs don't look right in high pixel densities because, for historical reasons, each app has to be written to support it.

If we picked a good default font size and made sure to properly support Windows' global UI scaling (including the high-DPI support in Windows 8.1) would that solve the problem? It'd be nice to follow the rules so that people don't have to adjust every program independently. Also, to keep the configuration as simple as possible. Let me know what you think.

Also, what resolution and physical monitor sizes are you using, as examples we can target? And what [global scaling](http://www.eightforums.com/tutorials/28310-dpi-scaling-size-change-displays-windows-8-1-a.html) options do you have configured?

**Comment by TimChippingtonDerrick** [comment]
Thanks for replying. We have a Lenovo Yoga Pro 2 and also a couple of Dell
4K 24" monitors as high-res displays We usually use the 100% scaling
option, as the whole point of getting a high res monitor originally was to
get more usable information on the screen. I could try to send some
photographs if that would help. Its not that dnGrep is unusable at all, and
it may also be true that my eyes are not as good as they were!. The paler
grey text also doesn't help the readability - but it does make the relevant
matching lines stand out well, so it has advantages as well as
disadvantages.

Tim

On 24 June 2015 at 17:32, JVimes <notifications@github.com> wrote:

> Thanks for pointing that out. I haven't tried dnGrep on a high-DPI display
> yet. I know a lot
> <http://www.hanselman.com/blog/LivingAHighDPIDesktopLifestyleCanBePainful.aspx>
> of programs don't look right in high pixel densities because, for
> historical reasons, each app has to be written to support it.
>
> If we picked a good default font size and made sure to properly support
> Windows' global UI scaling (including the high-DPI support in Windows 8.1)
> would that solve the problem? It'd be nice to follow the rules so that
> people don't have to adjust every program independently. Also, to keep the
> configuration as simple as possible. Let me know what you think.
>
> Also, what resolution and physical monitor sizes are you using, as
> examples we can target? And what global scaling
> <http://www.eightforums.com/tutorials/28310-dpi-scaling-size-change-displays-windows-8-1-a.html>
> options do you have configured?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dnGrep/dnGrep/issues/226#issuecomment-114934662>.
>



-- 
Dr Tim Chippington Derrick
Chippington Derrick Consultants Ltd
Tel: +44 01276 508949
Mob: +44 07971 997948

**Comment by JVimes** [comment]
Thanks for that. For whoever handles this issue, I think we should:

* Check our high-DPI support
* Check our global scaling support (both kinds, per Windows 8.1)
* Make sure our UI -- and particularly the results pane -- follows basic design guidelines for readability: font type, size, color, contrast with line background color, etc.
* Perhaps we should highlight hit-lines with a background color instead of font color?
* If we decide the results-pane font size should be configurable, support Ctrl+ScrollWheel zoom and put the setting under the User Interface tab of Options. Let's not support font type or color configuration at this time, but pick good defaults stead.

**Comment by doug24** [comment]
This was a pretty big change in the 2.9.24 beta, and would like know how it is working for people.  

I chose not to add new fonts or colors, as there are already a few colors in use in this window.  Overall, dnGrep now uses the system defined font and size, which cleans up the look of the window.  Thanks to John for helping out on that.  

I tested on a couple different Windows 10 boxes, and it works well well with different screen resolutions, high resolution monitors, per-monitor scaling (where each monitor has a different resolution and percent scaling).

I added zoom scaling to the results window:  using mouse wheel, touch screen, or touch pad, you can zoom the size of the text in the results window in and out.   With a touch screen, you can pinch to zoom.   With a mouse wheel, press the ctrl key with the mouse wheel.   With a touch pad, press the ctrl key and slide two fingers up or down on the touch pad.  There is a new context menu item to return the scaling to 100%.

**Comment by JVimes** [comment]
The zoom feature addresses this issue, perhaps better than font size would have, because the zoom feature also scales the tree control (icons, triangles). Side note: currently, users might want to turn on "Enable ClearType" to avoid pixelation when zooming (#251). It sounds like we're obeying the rules for UI scaling, high DPI displays, etc., so I'll close this issue for now.
