### ISSUE TITLE
Chocolatey pacakge

### ISSUE THREAD

**Issue by majkinetor** [dnGrep/dnGrep#233]
I created the automatic chocolatey package which is available here:

https://chocolatey.org/packages/dngrep/2.8.16

(it will get approved in next few days).

With it users of dnGrep can install it by simply typing `cinst dngrep`.

Please keep the format of [releases](https://github.com/dnGrep/dnGrep/releases) section the same as the package update depends on it. If you have to change it, please let me know in this issue.

**Comment by JVimes** [comment]
Hey, that's great. Thanks! Did you use GitHub's [releases API](https://developer.github.com/v3/repos/releases/)?

The releases are published directly from the continuous build to GitHub, so that should be stable for some time. Eventually, I want to use Squirrel to deploy instead of Windows installer (#216). We'll have to talk then. But I don't have immediate plans to tackle that.

**Comment by majkinetor** [comment]
> Did you use GitHub's releases API?

No, I download releases page via Powershell and parse out the stuff I need. Thanks for the tip, I checked it out and it works nice. I am surprised checksum is not available via assets API.

**Comment by JVimes** [comment]
Ya, I wish checksums were automatic. Had to paste those in myself. 😛

**Comment by majkinetor** [comment]
Anyway, its approved now so you can test it out. It also handles dotNet dependency automatically if you don't have it.

**Comment by JVimes** [comment]
Nice. It just worked for me :)
