### ISSUE TITLE
Make match count more verbose

### ISSUE THREAD

**Issue by sergeevabc** [dnGrep/dnGrep#243]
Version: 2.8.16 x64

Query: ```\blove\b```
Output: ```Christ, the Lord!  3 love, be in love with, cherish, fancy,```

Love is found twice, hence (2) in round brackets in output window near filename. So far so good.

However to stay in compliance with prominent CLI greps, which count number of lines containing matching queries (1 line in this case), stats should be more verbose (e.g. X matches in Y lines). Otherwise it leads to confusion when one compares the quality of search just by looking at count values (2 here vs 1 there).

**Comment by sergeevabc** [comment]
Could you confirm the issue is relevant?

**Comment by JVimes** [comment]
Relevant to the user base, you mean? I wish I knew, and I'm curious what others think. I can repro, and I like this suggestion. I'd take a look at a pull request on this one. Seems like a safe addition.

**Comment by sergeevabc** [comment]
@JVimes, does it mean you yourself withdrew from direct participation in development of dnGrep?

**Comment by JVimes** [comment]
@sergeevabc, I contribute to the project as much as I have time. For example, I'm triaging the issues you've submitted and I'm willing to review a PR on this one. dnGrep is driven by whoever contributes, including you. You can read more about the concept [here](https://guides.github.com/activities/contributing-to-open-source/), if needed.

**Comment by sergeevabc** [comment]
Had user been able to polish reported roughness himself, he would be called a developer, right? :)
But since the project is not marked as abandoned, I believe, even vague estimates on issues should be.

**Comment by JVimes** [comment]
You contribute issue reports. I contribute triaging and some PR reviewing. Hopefully someone will contribute development. Remember to be polite on GitHub.

**Comment by sergeevabc** [comment]
Well, there is no harm to ask, right? And honest _no_ is better than _someday_ for one who values time.

Let me explain.
Core value of open source philosophy besides freedom to look inside is to make life easier voluntarily.
And making life easier means doing, even with loose schedules and vague roles, not procrastination.
Otherwise project should be marked as abandoned to strangle public expectations at birth.
Want to share something with no further responsibility? Mute the feedback in the first place.

**Comment by JVimes** [comment]
Hey, don't get mad at me. I'm a user who volunteers some time to try to help. I don't own dnGrep, I've just been added as a member. I know it's frustrating that I don't know the answer to your question. You can see from the [pulse page](https://github.com/dnGrep/dnGrep/pulse) that dnGrep isn't very active. But it's not abandoned as long as the build still works and one person can donate some time to review pull requests. The issues you've reported are good, and I hope developers with some free time show interest.

**Comment by doug24** [comment]
I added this to the 2.9.21 beta.  I made it an option, and it is enabled by default - but you can revert back to the original behavior.   There may be some small performance hit, but I haven't noticed any on my systems.  But with large files, long lines, many hits, and slow disks it could be noticeable.  

After making the change for 2.9.21, I found a problem showing the line count when in multi-line mode.  That has been fixed in the next pull request, and will be available in the next beta.

**Comment by JVimes** [comment]
Thanks, @doug24. I hate adding another configuration option, but I understand the concern. Is the multi-line fix in 2.9.24? Looks like it counts a multi-line hit as "on 1 line"

**Comment by doug24** [comment]
Yes, it does count 1 match across multiple lines as "on 1 line".  I'm not sure what the right way to do this but it was the easiest to code :)   I think if you are doing a multi-line search (via grep or plain text) you expect to have matches on multiple lines.  And then there is XPath...

The problem I fixed in 2.9.24 was more obvious:  in 2.9.21 it was reporting 1 match on 0 lines.

**Comment by JVimes** [comment]
I think it's a sensible solution. If we word it more accurately, it'll be unintelligible.

Verified implemented.
