### ISSUE TITLE
Not picking up text

### ISSUE THREAD

**Issue by harryray33** [dnGrep/dnGrep#308]
I have a .bin file (below is a section of the file) ......I did a dngrep search. Whereas a search picked up '**ZþYO¾**' it did not pick up '**s e c t o r . b i n**'

Any thoughts please?

?'kóÿÿÿÿÿÿÿÿÀÆgbÔå"¿˜­ÿÿÿÿÿÿÿÿ üçbÔŸö_@¦üÿÿÿÿÿÿÿÿ oôÚbÔÇæ‚x@®l,ÿÿÿÿÿÿÿÿ·Ÿ4bÔÿOóg{Ëÿÿÿÿÿÿÿÿ ìqÐbÔënÂÀ÷¥ýÿÿÿÿÿÿÿÿPøp¶bÔ»ZþYO¾‹ÿÿÿÿÿÿÿÿ ž½žbÔç•Øâhfpÿÿÿÿÿÿÿÿ        ÅK˜“ÛXµ        ¾-a1„Éj¥Nä§¨}ªÊ…¬=w5ñý~>ò¿þv–ÄEp Sé/ÂÙt³ãõì®ÑB»?Æ<˜ÿ|RîqkœÔ9ñ­ÜSW¤wAnù
Û…>©ç«,Ö×ÊûQÌ¿-)h(ƒiÌ“¾|ÑâGÂ%iMó                _©]†–›                                                                                   ÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿÿ   )   D : \ p r o g r a m m e s \ i s o ' s \ A R 4 U S B \ 2 n d _ s e c t o r . b i n <

**Comment by doug24** [comment]
My guess is that those are not spaces between the characters in 'sector' - that's just how your editor is showing it.   The text probably encoded so that each character is two bytes wide. You could verify this by opening the file in a hex editor and see what value is between each of the characters.  One way to do this is open the file with GVim, and then do Tools : Convert to HEX.  My guess is that "sector' going to look like this:
7300 6500 6300 7400 6f00 7200
where the first pair is 's' (73 and 00), and second pair is 'e' (65 and 00), and so on.

The rest of the file you show there is not text, even the 'ZþYO¾' which are bytes that happen to map to characters that look something like text.  

So I don't think you are going to be able to use dnGrep to search in these files.

**Comment by doug24** [comment]
No there is not any way to be able to match both.  One is encoded with two bytes per character, and the other is encoded with one byte per character.  dnGrep reads the whole file with one encoding setting, so it will be either grouping characters as either one byte or two bytes.
