### ISSUE TITLE
Feature request: add option to use ripgrep

### ISSUE THREAD

**Issue by majkinetor** [dnGrep/dnGrep#355]
As you might know, [ripgrep](https://github.com/BurntSushi/ripgrep) is fastest of all greps. 
You could consider providing an option to use it as a search variant provided `rg.exe` is available (similar to how Everything is used).

Combined with dnGrep features, it could be awesome replacement for [ripgrep-all](https://github.com/phiresky/ripgrep-all) which also handles PDFs, archives and other stuff.

**Comment by JVimes** [comment]
If ripgrep-all is more mature and robust than dnGrep, maybe it's worth considering as a back-end for the UI.

**Comment by doug24** [comment]
Not sure how to respond to this.  I agree the .NET regex library isn't a standard implementation with it's own quirks, doesn't handle some regex syntax, and no doubt not the fastest, either. I have thought before about abstracting out the regex engine in dnGrep, and I'm sure it would be a lot of work.  

But the problem is that ripgrep is an application, not a library.  It does all the file system operations and file searching, returning a bunch of text to standard output.  That's really different from the way dnGrep currently works with files and makes regex calls.

Yes, someone could create a user interface to wrap calls to ripgrep, parse the output and do file operations with the results, but that would be substantially different from what dnGrep is now.

**Comment by JVimes** [comment]
Does ripgrep have an API? Is VSCode parsing output meant for humans?

**Comment by majkinetor** [comment]
There is a [json output](https://www.mankier.com/1/rg#--json). See [example](https://docs.rs/grep-printer/0.1.3/grep_printer/struct.JSON.html#example)

**Comment by doug24** [comment]
From what I see, there is no API.  The rg.exe binary is installed with vs code in the /resources/app/node_modules.asar.uppacked/vscode-ripgrep/bin directory.

They are reading stdout and stderr for the results.  Yes, they are using the --json flag to format the results.

There is a parser 'RipgrepParser':  in \vscode\src\vs\workbench\services\search\node\ripgrepTextSearchEngine.ts

**Comment by JVimes** [comment]
If the errors are also JSON, that works as an API. But it's for ripgrep, I don't know about for ripgrep-all. We'd have to test performance with tons of results.

It would be worth looking into, but I think it's lower priority right now. I'm mostly absent, so it really depends on Doug's interests. Thanks for bringing ripgrep to our attention, @majkinetor.

**Comment by doug24** [comment]
Of course it doesn't have to be me - anyone can submit a pull request.

I'm not not going to be working on this anytime soon.  Not because I don't think it has merit, but simply because of how much work it would be.  There is a lot of overlap and it's different enough that it would substantial rework of the existing dnGrep code.
