### ISSUE TITLE
dnGrep leaves multiple winword.exe processes running

### ISSUE THREAD

**Issue by jrmain** [dnGrep/dnGrep#356]
I just started using dnGrep and noticed that when it tries to scan some older Word documents, Word shows a warning. This warning dialog is not shown in front of foreground windows, and there's no corresponding entry in the taskbar. Until the OK button is clicked on the dialog, dnGrep appears to be hung.

I realize that this is more of a Word problem than a dnGREP problem, but it's significant. Before I realized what was going on, I was closing dnGREP, assuming it was hung. This also left multiple orphaned WINWORD.EXE processes running.

Here's the contents of the dialog shown by Word:
> You are attempting to open a file that was created in an earlier version of Microsoft Office. This file type is blocked from opening in this version by your registry policy setting. This error occurs if you try to open a Microsoft Office document and the file type for that document has been blocked by a registry policy setting. To help secure your computer, Microsoft or the administrator of this computer implemented a registry policy setting that prevents opening this type of file. To open documents with this file type, disable the registry policy setting. For more information, see Microsoft Knowledge Base article 922850.

**Comment by doug24** [comment]
dnGrep uses a plug in to scan Word *.doc files, and a different plug in to scan the newer *.docx files.  
Because this plug in uses COM automation, there is very little we can do in dnGrep to work around problems like this. 
 
You should disable the MsWord plug in: (the OpenXML plug in will still work for newer Word documents):

Open the file C:\Program Files\dnGREP\Plugins\dnGREP.Engines.MsWord.plugin in a text editor
In that file, change the line Enabled=True  to Enabled=False, and save the file.
If you have admin permission problems, you can copy the file somewhere else, edit it, can copy it back.

**Comment by jrmain** [comment]
Okay, thanks. That fixed the problem. dnGrep can still search DOC files, but matches are displayed as binary, which is fine.

**Comment by jrmain** [comment]
I was able to fix the original issue and re-enable the DOC plugin. I used the instructions on this Microsoft support page: https://support.microsoft.com/en-ca/help/922849/opening-a-file-is-blocked-by-your-registry-policy-setting-or-file-bloc
