### ISSUE TITLE
Suggestion: save search options after its changing

### ISSUE THREAD

**Issue by kvknyazev** [dnGrep/dnGrep#371]
Hi!
Since dnGrep does not support multitab, i use several instances, and i should config settings every time when i need to search other word. It will be useful to save setting after its changing.
Thanks

**Comment by doug24** [comment]
I also often run multiple instances of dnGrep, on different directories, or with different file filters and search text.

Currently settings are saved when you exit, or when you change something in the Options dialog and save.

I'm not clear: you want to save the settings (source directory, file filters, search text, search options, etc.) after every field is changed?  And you would do that so the next instance of dnGrep you start has a copy of those settings?  

Or are you suggesting that all running instances of dnGrep would also automatically read and load those settings?  -- that wouldn't work: the other instances would then change their settings to match the first, and then they would all be the same.

**Comment by kvknyazev** [comment]
> I'm not clear: you want to save the settings (source directory, file filters, search text, search options, etc.) after every field is changed? And you would do that so the next instance of dnGrep you start has a copy of those settings?

Yes, exactly what i mean. I want that new instance of dnGrep was started with the same search settings. 
May be add parameter to options like "Save changes immediately".

**Comment by JVimes** [comment]
I think saving state continuously might be a better user experience. I often wish Visual Studio did this, because sometimes it freezes and I have to kill it, and then recent state changes get lost.

**Comment by doug24** [comment]
In the current implementation, the settings are loaded from file only at the start up of the application.
The settings are saved to file on these events:
1) When opening the Options dialog
2) When clicking the Save button in the Options dialog
3) When opening the Regex Test dialog
4) On application exit

All running instances save settings to the same file, and overwrite the settings saved by the other dnGrep instances.  Last one wins. 

But to this request:  I don't think it is practical to save the settings after every property change:  there are about 34 properties saved on the main form.  The property changed event is raised when the value changes - which for text fields means on every keystroke.  So that is a lot of calls to save the settings file.    

I think it would be better add a call to save the settings when the "Search" button is clicked in addition to the four listed above.  I think that will keep it pretty current.

**Comment by kvknyazev** [comment]
> I think it would be better add a call to save the settings when the "Search" button is clicked in addition to the four listed above. I think that will keep it pretty current.

Yes, it will solve my problem.
Thanks!

**Comment by doug24** [comment]
fixed 2.9.181
