### ISSUE TITLE
Alterations?

### ISSUE THREAD

**Issue by ShadyGaDa** [dnGrep/dnGrep#382]
I'm impressed with your search utility. I downloaded source but was a bit lost when it comes to altering some of the controls and parameters as there are so many variegated formats and sub types.
The main questions would have been :
 (A): To set or change a '**universal font**' for the program.
 (B): How would i go about setting the syntax in the '**Replace Text**' dialog, so the format would stay the same as i go though '**Next**' and '**Previous**' files.
 (C): In the '**Replace Text**' dialog i would like to launch the '**custom file editor**' and also be able to exclude from results on that dialog.

**Comment by doug24** [comment]
A) You could set the Font and other properties on each Window by defining a style as [described in this answer](https://stackoverflow.com/a/50724592/602499).  The style would go in Styles.xaml.   We don't do that in dnGrep because we allow it default to the standard font for each version of Windows (and not all fonts are available on all supported versions of Windows).

B) In the ReplaceViewModel.cs, line 177 the CurrentSyntax is set to "None" when the file selection is changed.  If you remove that line, the CurrentSyntax will stay the same as you cycle through the files.

C) To open a file using the custom editor, you would need to something like what is done in the MainViewModel.cs "OpenFile" method.  But, you can't call that from the Replace window, and you would need to get the arguments from the data available in the ReplaceVeiwModel.
'Exclude from results' is a context menu on the main results tree, and te handler is "ExcludeLines" in ResultsTree.xaml.cs

**Comment by ShadyGaDa** [comment]
Thanks for your speedy, concise reply.
I shall try these solutions.
On (**C**): A merge of these two windows, possibly to a tabbed display might assist in the sending and receiving of internal commands.
The latter only an afterthought.
Thanks again.
PS. I do like the theme ability of WPF/cs/XAML/xml etc. 
Very reminiscent of delphi/pascal (embarcadero).
