### ISSUE TITLE
Layout design suggest

### ISSUE THREAD

**Issue by kvknyazev** [dnGrep/dnGrep#409]
Hello!
Thanks for dnGrep, it is very helpfull for me!
Can you think about adding layout selection?   Search options takes too many space on the screen. After search is done it is not optimal space usage. It will be great if you add capability to select how to split layout. I prefer vertical split with option to auto hide search options, like VS Solution Explorer.
Thanks!
Best regards, Konstantin Knyazev
![dnGrep](https://user-images.githubusercontent.com/34535317/76398475-fdee1a80-638d-11ea-89be-ddf34886b417.png)

**Comment by Csavie** [comment]
+1

**Comment by shawnkhall** [comment]
The search type should be removed from the collapsible and placed between the `More` expander and the `Search in archives` checkbox. This would save quite a bit of space for most searches where the extended options aren't necessary.

![dngrep-shorter-more](https://user-images.githubusercontent.com/6037167/132796168-8544a0e1-3443-4d2c-af02-334da53492be.png)

**Comment by doug24** [comment]
I appreciate the suggestion, but clear space isn't easy to find.  Since you are running in Everything mode, there are fewer controls on the right side of the screen.  And lots of people use the preview window, which takes horizontal space.  The area to the right of the `More...` button is used to summarize the settings in the collapsible panel, and can get long.  So I don't see how I can move them without moving or removing something else.   Here's what my normal layout looks like:
![image](https://user-images.githubusercontent.com/17227248/132872037-77afbfe1-833a-4cb3-b932-0addf2256520.png)
