### ISSUE TITLE
Installation of dnGrep 2.9.241 failed

### ISSUE THREAD

**Issue by AxelMarckx** [dnGrep/dnGrep#423]
The setup-program rolls back the changes it made. This is written into the Event Log:
Product: dnGREP 2.9.241 (x64) -- Error 1721. There is a problem with this Windows Installer package. A program required for this install to complete could not be run. Contact your support personnel or package vendor. Action: RunWarmUp, location: C:\Program Files\dnGREP\, command: "C:\Program Files\dnGREP\dnGREP.exe" /warmUp

**Comment by doug24** [comment]
At the end of the installation, there is a step to start dnGrep in the background - but it failed to start.  This has been in the installer for years, it's not something new.  

Did you try more than once?
Is this a first time installation?
If not, what version is being upgraded?
What version of .NET runtime do you have installed?

**Comment by AxelMarckx** [comment]
Hi,I tried several times, even rebooted my PC several times. No luck.It is not a first time installation. My current version of dnGrep is 2.9.229.0.My .Net runtime version is 4.0.30319.I am running Windows 10 64bit and have full administrator rights.I hope this information helps to solve the problem.Kind regards.
    On Thursday, April 16, 2020, 04:28:11 PM GMT+2, Doug P <notifications@github.com> wrote:  
 
 


At the end of the installation, there is a step to start dnGrep in the background - but it failed to start. This has been in the installer for years, it's not something new.

Did you try more than once?
Is this a first time installation?
If not, what version is being upgraded?
What version of .NET runtime do you have installed?

**Comment by doug24** [comment]
The minimum .net runtime required to run dnGrep hasn't been changed in two years, so that doesn't seem like it should be a problem.  The required version is .net 4.6.2 -  the version number 4.0.30319 doesn't have enough information to tell what you have installed, but [you can check using the notes here](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed).

Since release 2.9.229 one new dll was added in 2.9.236, but doesn't appear to be a problem for anyone else.  Otherwise I don't know of any changes that could affect the app from starting.

Is there anything in the dnGrep log file?   Find the latest Grep_Error_Log.xml in C:\Users\username\AppData\Roaming\dnGREP\logs  

Did you try installing 2.9.236?   

Does your 2.9.229 release still run?

**Comment by AxelMarckx** [comment]
Hi,
My 2.9.229 release was still ok. When I tried installing release 2.9.236, dnGrep told me this wasn't possible "because a newer version was already installed"! So my guess was something got completely corrupted. I completely uninstalled dnGrep, removed the directory C:\Users\username\AppData\Roaming\dnGREP, and then did a fresh install of release 2.9.241. Now everything works well again and I'm at the latest version.
Thank you for your support and keep on the good work. dnGrep is really the best windows grep utility I know.


    On Sunday, April 19, 2020, 03:47:32 PM GMT+2, Doug P <notifications@github.com> wrote:  
 
 


The minimum .net runtime required to run dnGrep hasn't been changed in two years, so that doesn't seem like it should be a problem. The required version is .net 4.6.2 - the version number 4.0.30319 doesn't have enough information to tell what you have installed, but you can check using the notes here.

Since release 2.9.229 one new dll was added in 2.9.236, but doesn't appear to be a problem for anyone else. Otherwise I don't know of any changes that could affect the app from starting.

Is there anything in the dnGrep log file? Find the latest Grep_Error_Log.xml in C:\Users\username\AppData\Roaming\dnGREP\logs

Did you try installing 2.9.236?

Does your 2.9.229 release still run?
