### ISSUE TITLE
better search pattern method without asterisks 

### ISSUE THREAD

**Issue by pstein** [dnGrep/dnGrep#460]
When I search for only certain files I tick "Asterisk pattern" and enter the pattern:

Unfortunately when I write

Log

dnGrep does NOT find files like "Proj1234 Log after step3.dat"

Users are forced to enclose it in Asterisks: *Log*

Thats uncomfortable. I oftentimes forget it and have to re-run it again.

Can the file search pattern method be changed?

According to general, common usage rules when users enter e.g. 

aaa bbb

then the file name (btw: INCLDUING) path) should contain aaa AND bbb possibly with other stuff between them
and possibly with opposite order.

If the user enters

aaa bbb !ccc

or

aaa bbb -ccc

then the same search as above should be performed but additionally without all the files containing "ccc"

Can this be implemented?

Thank you
Peter

**Comment by doug24** [comment]
If any other dnGrep users are watching these issues, I would like to see your comments or votes.   I don't want to add complexity to the program and spend my time on something that few people would use.

I think this would have to be implemented an alternative file filter in addition to the three existing options of Asterisk, Regex, and integration with the Everything application.  I think it would be too problematic to make it work with the Asterisk pattern - it would give unexpected results to someone who is used the asterisk pattern.

This sounds more like the search feature in Windows Explorer.  Personally, I do not like this kind of filtering because I think it matches too much and returns results I don't want.

**Comment by TimChippingtonDerrick** [comment]
I'm not a fan of 'simplified' search - I never seem to know what it is
going to match. That is one of the reasons that I use dnGrep - I can
specify what I want to search for with some reasonable confidence about
what will or won't match
Just my 0.02 euros
Tim

**Comment by JVimes** [comment]
This is for the file filter, right? Not the grep query.

I think what you're describing is some form of [fuzzy matching](https://en.wikipedia.org/wiki/Approximate_string_matching) and it's different than [wildcard (aka "glob") pattern matching](https://en.wikipedia.org/wiki/Glob_(programming)). It would be a new, alternative mode for file matching.

It's a valid feature request, but I question the cost vs benefit since Doug is the only dev contributor right now.
