### ISSUE TITLE
How to EXCLUDE directories and files?

### ISSUE THREAD

**Issue by tobwz** [dnGrep/dnGrep#491]
Assume I want to search in all files on my partition  D:\ except the subdirectories D:\temp\ and D:\data\ and except the files matching *.sys and *.exe and *.tmp

How can I achieve this?

I miss two extra entry fields:
- Exclude directories
- Exclude files

Can these be added?

**Comment by doug24** [comment]
In Paths to match: `*.*`
In Paths to ignore:  `*.sys;*.exe;*.tmp;\temp\*;\data\*`

Both inputs take comma or semi-colon separated lists of patterns.

**Comment by logicalextreme** [comment]
Sorry to hop on to this — to use your example above, how would you exclude a directory called `data` that's in the _root_ of where you're searching (i.e. the path in the "Folder" textbox), while including any subdirectories called `data`? I've tried every way I can think of with glob patterns but it either excludes them all or includes them all.

I've tried using the regex option for path patterns so that I could use `^` to indicate the start of the path, but I can't get any search results at all when using that (paths to match = `.*` and paths to ignore = empty).

**Comment by doug24** [comment]
I don't think you can do exclude just the root directory using asterisk patterns because when you use a pattern like `\data\*` you will exclude the `data` directory and everything below it.  

I was able to use a regex pattern.   Let's say you have these files.  It's important to note that the pattern matching is done on the full path, not just the part below the root directory.

    C:\Repos\testFiles\test\test.txt
    C:\Repos\testFiles\test\test.log
    C:\Repos\testFiles\test\depth1\test.txt
    C:\Repos\testFiles\test\depth1\test.log

To exclude the root level files, you are trying match the first two strings, and not match the second two strings.  Here is one that works:
`\\test\\[^\\]+$`

This will match (and exclude) files only if there are no additional backslashes between 'test' and the end of the string

Or you could use this if you only want to exclude txt files at the root.
`\\test\\[^\\]+txt$`

You can try it in dnGrep's regex tester:

![image](https://user-images.githubusercontent.com/17227248/109672044-7a42b600-7b29-11eb-832b-c3f6684b55b5.png)

**Comment by logicalextreme** [comment]
Thanks — what I actually meant was that given the below:

```
C:\searchroot\data\test.txt
C:\searchroot\data\test.log
C:\searchroot\other\data\test.txt
C:\searchroot\other\data\test.log
C:\searchroot\stuff\data\test.txt
C:\searchroot\stuff\data\test.log
```

I'd want to exclude only the top two (i.e. the top-level `data` directory), but include any subdirectories with the name `data`, whereas a `\data\*` glob filter excludes all of them. Your explanation about the pattern matching happening against the full path makes sense, I can just fully-qualify all of the exclusions — I thought that GNU `grep` directory exclusions worked relative to the directory being searched, but they're a lot more basic than that and I've actually realised that there's no way of doing what I want in `grep`, meaning dnGrep is more powerful :)

As for the problem I was having getting regex path patterns to work, it seems to be a bug related to the .gitignore option (it works on non-repo directories, or if I untick that option) — I'm not too bothered as I have a solution now but if I get the chance I'll play around with it and open a bug if I find out what's causing it (I'm presuming it's due to something in this `.gitignore` file).

Thanks for the response, and the software 🙂
