### ISSUE TITLE
Insufficient memory issue

### ISSUE THREAD

**Issue by StealerCook** [dnGrep/dnGrep#499]
Hi,
dngrep is showing "insufficient memory to continue the execution of the program". 
Is there a way to solve this issue?

**Comment by doug24** [comment]
Never seen this.  
Is this during the search or viewing results?
You could try:
turning off the preview pane (which loads the whole file)
limiting the number of files expanded in the results tree
maybe unchecking the 'Search parallel' option

**Comment by StealerCook** [comment]
Thankyou. I tried with those, but not working .
![Check](https://user-images.githubusercontent.com/76549252/114393368-91100a00-9bb7-11eb-9343-5ee99cdee1bc.jpeg)

**Comment by doug24** [comment]
How big are those files?  
What is the file type?
Are you doing a Multiline search?  Or XPath?
 -- these options require the whole file read into memory, otherwise files are processed line by line which uses a lot less memory.
 
Are you running 32 bit or 64 bit?
how much RAM do you have, and how much is free?
Is you disk full?

**Comment by StealerCook** [comment]
Yea Thankyou. Working fine when unchecking Multiline search option.
