### ISSUE TITLE
Ctrl-a (for 'select all') doesn't select all results

### ISSUE THREAD

**Issue by oddwing** [dnGrep/dnGrep#508]
When I press Ctrl-a to select all of my search results, only the first two page lengths are selected (around 58 results). If I page down twice and hit Ctrl-a again, the next two page lengths are selected. To truly select all search results, I have to page through all of the results. This gets tedious when there are many results.

**Comment by doug24** [comment]
Yes, that is a bug.   When you do first select all, it's only getting the current set of tree nodes.  The search results tree dynamically creates and removes tree nodes as you scroll to save memory and improve performance.  This is done to protect against creating large numbers of tree nodes, which can lock up the app.  Not sure what the best way to fix this.

Just wondering if there is another solution to the problem:  after you select all, what are you doing with the selected items?

**Comment by doug24** [comment]
Does anyone have an opinion of what "Select all" means? 

The search results is a tree, with the file at the top level, and the set of matches within the file at the child level.   Can we say that "Select all" means all the file nodes, but doesn't include the collection of all child nodes?

**Comment by doug24** [comment]
Fixed in Release 2.9.345

I decided to make 'Select all' select all the file level tree nodes and also select all the line results, if they are expanded in the tree.  I think this gives the user the most control over what information is selected.

Because the line level results are lazy loaded in the tree, I did not want Select all to force loading all the line results just to select them.  But if you need to, you can expand all the nodes and then select all.
