### ISSUE TITLE
Typo - 'RenameFile'

### ISSUE THREAD

**Issue by celeron533** [dnGrep/dnGrep#555]
`RenameFileL`
https://github.com/dnGrep/dnGrep/blob/177942b504b79b7a5a54f58f2e7f9b18cf90d5ba/dnGREP.WPF/UserControls/ResultsTree.xaml#L153

also in resource file.

**Comment by doug24** [comment]
@celeron533 @ronen1n @StoyanDimitrov   I wanted to highlight this and issue #550.   

There are going to be issues that come up when accommodating differences in languages, and we will fix them as we find them.  My thinking is that we'll add new keys and reduce the reuse of keys in different locations if it makes more sense in different languages.  I make all languages as natural as possible.

In this instance, I did this intentionally:  there are two keys `RenameFile` and `RenameFileL` used in different places in the application.   In English, the first maps to "Rename File" (both words upper cased) and is used on the title of a dialog box.  The second maps to "Rename file" and is used on a context menu where generally only the first word is capitalized.  So, yes, it's a pretty minor point, but I'd like to leave it this way, and you can map both keys to the same text in other languages.  There are a couple of others like this, as I recall.  We can fix the naming, if that helps.

**Comment by StoyanDimitrov** [comment]
I personally know that is a **huge** amount of work to annotate the strings the way it will be beneficial for translators. This situation could be avoided if translators are provided more info about how and where strings are used in the UI - button label, text field placeholder, window title, menu item. Simple as it seems it brings the missing context of the string.

I'm not accusing anyone. It's just the start of the translation journey of the project.

**Comment by doug24** [comment]
I appreciate the input, and didn't expect that I got it right on the first try.

I tried to add annotations in the resx comments / transifex developer notes, but I can see how that doesn't go far enough.

When I extracted the string resources, I tried to maximize the reuse of a string resource to as many locations as possible.  But now I'm wondering if the resources should be unique to one and only one location in the application.  Then the annotation could specify the exact location.   Yes, this would be a lot of work, but I've already put a lot of hours into this.  If I had copies of your current translations, I could update them all at the same time so you wouldn't lose any work, but you will likely have to add more or copy from other resources after I'm done.   I could probably do these changes this weekend.

Any thoughts?

**Comment by StoyanDimitrov** [comment]
> I appreciate the input, and didn't expect that I got it right on the first try.
>
> I tried to add annotations in the resx comments / transifex developer notes, but I can see how that doesn't go far enough.

My comment wasn't meant to critique your work in any aspect. Quite the opposite! I am impressed by the fact that every string have corresponding comment! Almost all of the translations I contribute to have none, nearly none or inadequate translator notes so we have to hunt strings down in the UI - a time consuming task (multiply that by the number of contributing translators).

> But now I'm wondering if the resources **should be unique to one and only one location in the application**.

Really, that's the only right way of doing it. (Emphasis mine.)
> Yes, this would be a lot of work, but I've already put a lot of hours into this.

It shows! Should I tell you how many projects have hot reloading translations?

> If I had copies of your current translations, I could update them all at the same time so you wouldn't lose any work, but you will likely have to add more or copy from other resources after I'm done. I could probably do these changes this weekend.

At this point do whatever is easier for you and don't think about translators. We will catch up as we have tools at our disposal to help with repeating strings. It will be much harder (in terms of psychological pressure) when we decided to make this change later and there are 20 (or 50) ready translations. It's a change for good. Do it and don't look back!

> Any thoughts?

I'm honoured to work with developer that dedicated to the community.

As you may already have guessed the comment/translator note is as equally important as the string itself as the translator doesn't know where the strings is shown in the interface, what is it (label, help text, description, title, call to action etc.) just by looking at it in the translation tool.

One last thing. And don't expect to do it right the first time (;

**Comment by doug24** [comment]
I have updated the resource keys and comments, and created a PR to update the application.

All of the resource keys have been changed. They are now grouped by application window, dialog box or message box. Each resource is used in just one place in the application - with two exceptions: the tooltips for Regex search and replace are reused in the Main window and the Test window.

All of the resource comments/developer notes have also been changed. Hopefully, they will be more helpful now to see where in the application the resource is used.

I removed the trailing underscore form the resource keys that had been used to indicate the string may contain an accelerator key. Instead, I added the (accel) tag to the end of the comment/developer note.

I uploaded the new resource keys with the Bulgarian and Hebrew translations to Transifex. All the translations that were done yesterday morning have been preserved/reuploaded with the new keys.

The order you see the strings in Transifex is sorted by key. Since all the keys are prefixed by the context, all the strings for a window are grouped together. You can see the key name in Transifex in the lower right part of the screen. The comments/developer notes are above the translation input field.

**Comment by celeron533** [comment]
Hi @doug24 ,
Since the resource file is updated, this issue does not exist anymore and there has some discussion and conclusion, shall I close this ticket?

**Comment by doug24** [comment]
yes, it can be closed.
