### ISSUE TITLE
Bug: Bookmarks don't play well with Everything search

### ISSUE THREAD

**Issue by shawnkhall** [dnGrep/dnGrep#556]
The Bookmarks feature doesn't populate the `Everything search` field from the `File pattern`. It looks like most other options are preserved, but that field is not.

Also, it would be more consistent if the Bookmark form layout more closely resembled the dnGrep search panes with "Search in" above `Type` and `Search/Replace`.

**Comment by doug24** [comment]
Long story, I'll try to keep it short.  Bookmarks were originally a way to save complicated regular expressions, and only a couple fields were saved in the bookmark.  Over time people asked to save more fields in the bookmark until most everything was included.  Then someone asked to associate a bookmark with a directory so every time you went back to that directory, the bookmark would be applied (which is good for things like log directories).  But the bookmark never saved the folder location because then applying the bookmark would change the search location, rather than setting search properties on the currently selected location.

Now with Everything, the search location and any number of file filters are all part of one field.  So it's different from the normal dnGrep search filters.

So I'm wondering, do you really want to bookmark the search location and have applying the bookmark change the location you are searching?  If so, I can make a change to save that field, but I would only be saved when the search is in Everything mode.  This also complicates the Bookmark details page as it should handle enabling/disabling fields depending on the search mode. 

I'm pretty busy right now with the translations, so this will have to wait for a release or two.

**Comment by shawnkhall** [comment]
I'm pretty much always in `Everything` mode, and while I understand your concern, it would really be perfect for how I've been using it. Using the `File pattern` from the bookmark as the `Everything search` query appears to be how it's intended to work. It just doesn't actually populate that field in the dnGrep interface when you select that bookmark. Everything doesn't really need a folder to work, and in many cases that complicates things unnecessarily. 

I've been using the search history dropdown to get the same result, but I have to do both the `Search in` and the `Search for` fields from their drop-downs and I'm afraid there's going to come a time when I use it so much that the older entries disappear on me. It's already difficult to keep them organized. For now, I'm planning to use the CLI interface to get the same effect as the bookmarks. This might even work better for my purposes since I automate everything else from the CLI. 

I'm coming from a File Locater Pro world where I would initially search using Everything to find the first result set then search in File Locator Pro/Agent Ransack to get context. It was very clunky. dnGrep is almost perfect and you're amazingly responsive to feedback. Best yet - it integrates directly into Everything so I don't have to waste time exporting and importing or have yet another index of my data to be able to get the results I'm after. It even supports direct integration for Notepad++ and Beyond Compare. You have *literally* saved me over 20 hours in the 2 or 3 weeks I've been using this program.

Things like this - preserving a bookmark of the relevant field values for a specific search, will make it even more efficient. Everything modifiers like `dm:` allow me to effectively replicate the `Past x hours` feature, but implement it in a bookmark. The best part of integrating the full `File pattern` into the `Everything search` is that I can bookmark stuff like `*.MAI dm:today size<120k` and then enter the search term in the `Search for` so I can immediately find any messages delivered today that were sent to one of my clients (for example). That doesn't appear to be possible with the bookmarks for other search types.
![todays-mail](https://user-images.githubusercontent.com/6037167/134290058-8d50d08f-7777-4440-ab41-0e5d80e0af9e.png)

As far as when it might be implemented - I'm in no hurry. Thank you!

**Comment by doug24** [comment]
The bookmarks have been modified in 2.9.400 to save the Everything query, and the Bookmark details layout is modified.
