### ISSUE TITLE
Pressing Cancel does not stop the search

### ISSUE THREAD

**Issue by mdell-seradex** [dnGrep/dnGrep#578]
Sometimes I start a search, but find that I have the wrong location, or wrong options.  I try to cancel it, but it many cases it appears to run to completion instead of stopping.
Often this is not a major pain, but sometimes I try to search everywhere (e.g. C:\), so being able to cancel when doing that would be very helpful.

**Comment by doug24** [comment]
I don't know what would cause this, when I test it, the search stops very quickly.   Can you share the file search settings and search pattern you are using?  Maybe it has something to do with some option that I don't have set.

**Comment by mdell-seradex** [comment]
Is this what you are looking for?
![Screenshot 2021-10-30 161239](https://user-images.githubusercontent.com/40300659/139557225-8f1b7ce5-9dba-42ea-9cda-65b6b239d71d.png)

**Comment by doug24** [comment]
I see now, the problem is enabling `Use .gitignore` from the drive root - dnGrep is going to search the entire drive for .gitignore files before it starts searching for files, and there wasn't a Cancel check in that code.  I can fix that.

**Comment by mdell-seradex** [comment]
Interesting.  I don't think I ever enabled that.

**Comment by doug24** [comment]
Fixed in Released in 2.9.428

**Comment by doug24** [comment]
I think the optimum way to use .gitignore is if the search start directory is a git repository, in a git repository, or possibly one level up if you want to include multiple git repositories.  It does not work well when searching from the root of the drive, or from a network drive because dnGrep needs to each the everywhere to find any git repositories before it can begin the search.

Searching for .gitignore starts looking at the starting point of the overall search, goes down the tree, and if not found goes up the parent folders to the root.  So if your search begins at the root, it will search the entire drive.

I added a status message when dnGrep is looking for .gitignore files to give users a indication of the cost of the operation.

Sometimes it is faster, and sometimes slower using .gitignore.   When searching a git repository, I find it very useful to include those file filters.  No, it would not affect any parent directories above the git repository.  

The 'Use .gitignore' is just for git, not TFS or Mercurial, but they could potentially be added in the future.  The way dnGrep implements this feature is to run a git command, asking git for the list of files and directories to ignore.  I didn't want to try to implement all the parsing rules and then build the exclusion list internally - it's far easier to just ask git to do it.

**Comment by mdell-seradex** [comment]
Thank you for the clarity.
I don't actually use git either, so I think I will simply turn off the option, but at least I understand a bit better now, and you have improved the app using my feedback.
