### ISSUE TITLE
[feature] to preview a pdf line of a searching result

### ISSUE THREAD

**Issue by Aliaksandr3by** [dnGrep/dnGrep#659]
as in analog
![image](https://user-images.githubusercontent.com/11432724/161180072-b0546152-cc48-496a-abd7-680c736aa9ca.png)

![image](https://user-images.githubusercontent.com/11432724/161179851-5552c7e6-956d-4e5c-bedc-bf6851cce62c.png)

**Comment by doug24** [comment]
dnGrep is a plain text search tool.  It has been extended to do text searches on binary files including Word, Excel, PowerPoint and PDF.  But it's always a compromise to extract plain text from a formatted document.  PDF is the most difficult because the file format is a bunch of typesetting instructions, not text with formatting like Word.

PDF is very useful for what it does well - rendering complex graphics on pretty much every operating system.  But as an input for searching plain text, it is pretty awful.  When dnGrep searches PDF files, it runs a third party application to convert the PDF to plain text, and searches the plain text file. The third party application does a pretty good job, but it isn't perfect.  And it gives no indication of where in the PDF document the text is.  So while it is possible to have something to show the PDF in a (different) preview pane, there isn't any way to correlate the text found in the plain text to the actual text rendered in the PDF window.  

I have searched for a better way to search PDF files, and have not found any viable options for a free application.   

So I'll put this in the probably won't fix category.

**Comment by Aliaksandr3by** [comment]
bad(
