### ISSUE TITLE
Bug Report: empty search criteria takes a very long time

### ISSUE THREAD

**Issue by BoxingLaunch** [dnGrep/dnGrep#663]
Sometimes I want to search only by filename, with no file content criteria (i.e., the "Search in" section's "Patterns to match:" fields are filled, but the "Search" section is empty.

When I do that, I just want a list of files returned in the results section. Instead what happens appears to be unreliable, with searches taking extremely long (as though the regex engine is searching each file extensively for an empty-string regex). 

I believe that the correct behavior if the "Search" section is empty should just be to list files matching the "Search in" section's criteria only.

**Comment by doug24** [comment]
This should be very fast.  Can you show an example of all the patterns and filters you are using?  Is there anything special about the root search path (are you including network shares or OneDrive folders)?  If you have 'Use .gitignore' checked, try without that.

**Comment by BoxingLaunch** [comment]
![25a07fe1-5a21-4f9d-8d6f-141605cefbe4](https://user-images.githubusercontent.com/94591609/163471494-a934cad4-b6a4-42a3-83dc-051bf2b966da.png)

Here are the search settings. It gets stuck on `File 1.pdf` (for example) for 10-60 seconds at a time, when it should be going insanely fast.

It is inside a OneDrive, but the folder is stored locally. I don't see a .gitignore option anywhere.

**Comment by doug24** [comment]
I stepped through the debugger, and I don't see that it's doing anything unexpected.  It is doing a binary check since you have 'Include binary files' unchecked, but that is very fast on local files.  It's also getting the file info to check the file size, but that is also very fast.  In my test I searched about 2000 files, and found 31 matching the pattern filter in 1.8 seconds.

About your file pattern regular expression:  when the 'Patterns to match' and 'Patterns to exclude' are regular expressions, the expression is applied to the full file path, not just the file name.  If you want to limit it to just the file name, you need to add a bit more to your filter expression. Also, since you didn't limit the 'pdf' to the end of the string, you will match 'pdf' anywhere in the string (as long as there is an 'insp' somewhere before it.  Just add a dollar sign at the end to match only pdf files:  `insp.+pdf$`

"File 1.pdf" may not be the file taking a long time.  With the 'Search parallel' option checked, the app will be processing multiple files.  "File 1.pdf" was probably the last file started, but there could be another file started earlier that is taking longer to process than it.

The "Use .gitignore" option is only visible if git is installed on your computer.

**Comment by BoxingLaunch** [comment]
Regarding the debugger stepthrough: Thanks for looking into that! I will try again unchecking the 'Include binary files' option and see if that makes much of a difference!

Regarding the patterns: That's great! Thanks for the info! That's what I was after, but helpful to have that laid out explicitly. 

Regarding parallelism: Makes sense! 

I will try again later on and see if I can figure out why it was taking so long or if I can help improve this report. For now, let's call it a non-issue though!
