### ISSUE TITLE
Bug: Regular expression evaluation

### ISSUE THREAD

**Issue by fade2gray** [dnGrep/dnGrep#691]
https://user-images.githubusercontent.com/1332009/173847306-daaab1db-31c6-41e5-bedf-1c400a4278ea.mp4

**Comment by doug24** [comment]
This doesn't look like a bug to me.  The initial expression is not valid because `\3` is not a valid regular expression. `\D` and `\d` are regular expression tokens:  `\d` matches any digit and `\D` matches any character that is not a digit.   Adding the second backslash escapes the token so that they match the literal string.  [Quick reference](https://github.com/dnGrep/dnGrep/wiki/Regular-Expressions)

**Comment by fade2gray** [comment]
Good catch - thank you.
