### ISSUE TITLE
why is the `Replace` button disabled?

### ISSUE THREAD

**Issue by gilbh** [dnGrep/dnGrep#701]
Love your project!

I am not sure why, but the `Replace` button on my dnGrep is disabled:
![image](https://user-images.githubusercontent.com/39532610/177191888-5e1c2766-b224-4148-bb0d-61e9f487c983.png)

I looked into the switched and can't locate the reason. 

Could you please assist me?

Thanks.

**Comment by doug24** [comment]
Is it ever enabled? What happens if you click Search again?
Some possibilities for why it is disabled:
- There are no search results
- All the search results are read only
- Some search parameter has changed since the search was run (replace reruns the search in the process of doing the replace, so this ensures that the replace parameters are the same as the last search completed)
- Boolean operators is selected, and the search type is not Text (Replace with Boolean operators is only implemented for plain text search)

**Comment by gilbh** [comment]
Thanks for the quick and detailed reply.

I ran this again and now it works, and I have no idea what has changed. Sorry for wasting time, but again -- let me thank you for a really superb application (in terms of UI, execution speed, etc.).

One thing to consider improving, I think, is the upgrade process, which involves a lot of user interaction (confirming, closing, downloading, etc.) -- I think it would be way easier to have an automated update a-la browsers, or something of that sort.

Thanks again and best!

I attach a screenshot.
1) There are search results.
2)
