### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by xenos-github** [dnGrep/dnGrep#758]
When using a date range is it possible to set the date format to DMY or YMD? If not, could this be added?

**Comment by doug24** [comment]
Are you referring to the date shown in the control with the calendar drop-down?  

If so, then I think the answer is no.  I tried some suggestions I found for doing that and they worked initially, but when focus leaves the control, the control reverts back to the default format.  That control is very difficult to work with, and I had lots of problems getting the watermark shown in different languages.

The default format is the "Short date" setting in the Windows Regional format settings.  You could try changing the format in the Windows settings, but that will affect all applications.  On Windows 11 you can change it in Settings > Time & language > Regional format -> Short date.

**Comment by xenos-github** [comment]
...but it reverts to MDY after using the drop-down calendar. :-(

**Comment by doug24** [comment]
The same problem I had when trying to override the format in dnGrep code. 

I spent some time looking at the reference source code for the WPF Date Picker control, and I really don't see any way around this problem.  It's formatting the date using the ShortDatePattern from current Culture setting or from the current language - it's not clear from the code which is getting used.  It seems like changing the short date pattern in the Windows settings would do it, but it looks like it is using the current language - and since the application is changing/setting the application language to show the translations, it is using default short date format for the current language.  

That gave me the idea of changing the short date pattern in the culture settings when changing the language.  And yet again, it has my custom format when it is first shown but reverts to the default format when the calendar is closed.

It seems that to change this would require dumping the standard date picker control and writing a whole new one. Way more than I can take on.
