### ISSUE TITLE
Window misbehaves upon launch

### ISSUE THREAD

**Issue by sergeevabc** [dnGrep/dnGrep#807]
Are you aware how dnGrep displays its window upon launch on my end?
It crawls under the top taskbar and goes beyond the lower border of the desktop.
System: Windows 7 x64, Windows Basic theme, 1024x768.

![2023-0111-2204 dngrep window 01](https://user-images.githubusercontent.com/373718/211896841-af08e1ca-7204-4631-a1f6-7dc560b6807f.png)

**Comment by doug24** [comment]
No, I'm not aware of any window layout/restore problems - it's been over two years since any of that code has changed.

Is this just on the first startup, or does it not restore to the size and position from the previous session?  If it is not restoring to your previous session, what are the values saved in dnGREP.settings.dat file for the "MainWindowBounds" and "MainWindowState"?

As far as I know, dnGrep does still run on Windows 7, but I have no way of testing it there and can't do any Windows 7 specific fixes.

**Comment by sergeevabc** [comment]
Aforementioned screenshot illustrates the position of the window upon the first launch after unpacking dnGrep when there is no dnGREP.Settings.dat. That file is created after I close the app. The values you asked about are as follows

```xml
<item key="MainWindowBounds">0,0,500,788</item>
<item key="MainWindowState">Normal</item>
```
I believe the developer forgot to add checking the position of the window on the screen and in general is too keen on twisting the standard Windows controls, hence this and similar issues like these

![2023-0112-0155 dngrep window 02](https://user-images.githubusercontent.com/373718/211935950-7b3fc513-590a-446d-b923-fb612e87f92b.png)

![2023-0112-0156 dngrep window 03](https://user-images.githubusercontent.com/373718/211935990-75780abd-5440-4301-a410-04a09ee29346.png)

Whereas the job of this particular app is not to be fancy, but to provide users more visual way to search and replace rather than immerse them in the darkness of command line with myriads of switches and arguments.

**Comment by doug24** [comment]
On initial startup when there are no saved settings, the initial window position is Left = 20, Top = 20, Width = 1200, Height = 800, and that's what I get when I run it with no saved settings.  There is code to check that the window is on a screen, using the screen working area.  That code should account for you having the taskbar on top.  But this app has only one developer, doing it in their spare time, and for no compensation.  I can't test every possible combination of displays, layouts and operating systems.  If you need that, purchase a commercial application.  Or fork it and make it work how you want.

I don't support Windows 7 any longer; I can't test it.  I do go to lengths to try not to break compatibility and there are a number of things in the code to provide fallback options for Windows 7 because I know there are users still running Windows 7.

The display issues you pointed out are from a missing font.  The app expects to have Segoe UI, which has been around since 2004 and can be installed on Windows 7.  

I don't consider anything in the app fancy.  Everything there is from something users have requested.  I've been criticized here for not using the latest technologies and not updating the app to latest standards, which would surely would not run on Windows 7.  I can't win either way.
