### ISSUE TITLE
Wrong replacement when using accents or some symbols

### ISSUE THREAD

**Issue by Wolf-Igmc4** [dnGrep/dnGrep#835]
Hello. I'm using dnGrep for the first time, and I'm not sure if it is because I have a wrong config or something (sorry if that was the case). When I try to replace some text, like " ¡Por favor, cuídate!", the program apparently doesn't recognise "¡" and "í" symbols, and replace them with "?", resulting on the following text: " ?Por favor, cu?date!"

It's strange because it doesn't happens always, but when it occurs and I continue to use dnGrep knowing it has happened, all the subsequent replacements that contains these symbols in the 'Replace with field' are all replaced with "?". This makes me think that it may have something to do with the files I'm working with, but not sure at all.

I'm translating files that work as a .txt by the way.

I'll attach an image showing a result. When I try to change it to " ¿Qué?" it changes it to the same one I have searched before (basically it doesn't change anything).

![image](https://user-images.githubusercontent.com/31896129/221364039-4e44183a-8383-404a-b4da-7ac8c50d7d1c.png)

Also, apparently the Test expression is working fine, but still it doesn't save it correclty in the file.

![image](https://user-images.githubusercontent.com/31896129/221368084-dcb1b447-c1b2-43a6-9c98-89a3b50dee41.png)

**Comment by doug24** [comment]
My guess is that this is a problem with detecting the character encoding of the file.  In the expanded filters section `More...` is an encoding selector.  The default is 'Auto Detection' and dnGrep will try to guess the encoding based on the characters at the start of the file. It may be returning the wrong encoding because of the mixture of languages.  

If you hover over the file name in the results list, the tool tip will show what encoding dnGrep is using for the file.

If you know what the file encoding actually is, set it in the drop-down.  Or try setting the encoding in the drop-down to UTF-8 or Western European (Windows).

**Comment by Wolf-Igmc4** [comment]
Thanks for the fast reply! I've tried setting the encoding to UTF8 and now it works alright 😄
