### ISSUE TITLE
Feature Request: Ability to search binary files only

### ISSUE THREAD

**Issue by fade2gray** [dnGrep/dnGrep#841]
Ideally, I would like to see an option to search within binary files only.

Alternatively, can you provide a list of extensions that dnGrep uses to identify binary files, perhaps adding them to settings, similar to the list of archive extensions - they could then be copy/pasted to `Patterns to match` field.

Or, maybe add the option to sort the search results by `[read-only]` - that would help.

Thanks.

**Comment by doug24** [comment]
dnGrep doesn't use file extensions to identify binary files.  To identify a binary file, dnGrep reads the first 1K bytes of the file and searches for two consecutive nulls.  This will be true for binary, and false for nearly all text files. The binary check is one of the most expensive file filters since it needs to open and read every file during the file search phase.

My suggestion is to create your own list of binary file extensions you encounter in your files and use them in the Patterns to match field, that will be much more efficient.

**Comment by fade2gray** [comment]
> dnGrep reads the first 1K bytes of the file and searches for two consecutive nulls

Having discovered that, I searched 2,000+ files for `00 Bytes` which returned a list of`[read-only]` files, from which I was able to filter the extensions.
