### ISSUE TITLE
Feature Request: Extra options for Search and Replace

### ISSUE THREAD

**Issue by fade2gray** [dnGrep/dnGrep#844]
1. An option to toggle the case of the search string between upper and lower case.
2. An option to preserve the case of the search result when applying the replacement string.
    For example, search for cat, with cat, Cat and CAT found as a result; to be replaced with dog, Dog and DOG.

Is this possible?

**Comment by doug24** [comment]
Item 1 - is this just to make the search text upper case or lower case (for doing case sensitive searches)?  If so, the text boxes have a context menu, and upper/lower case commands could be added there.  I somehow missed this context menu when doing both the color theme and translations, so it needs to be updated.

Item 2 - I'm guessing this is for identifiers in code? My first thought is what to do about Camel case and Pascal case strings? - there isn't any way to modify the replacement string in the same style.  Otherwise it would be possible, but it seems it will have limited utility and be a lot of work to implement.  You can already do this using case sensitive searches.

**Comment by fade2gray** [comment]
Item 1 - Yes, just the ability to toggle the search term between all lower and all caps for case-sensitive searches.

Item 2 - I understand the difficulty with this, so maybe I'll just stick with the script I use for such replacements.

Thanks.

**Comment by doug24** [comment]
Added the Make Uppercase and Make Lowercase in v3.2.306
