### ISSUE TITLE
dnGrep cannot search for the following scenario.

### ISSUE THREAD

**Issue by jbxenzxy** [dnGrep/dnGrep#870]
If I want to search "then build the", it don't work.

![11111111111111111111](https://github.com/dnGrep/dnGrep/assets/40913849/683f7e70-effa-4a1e-a81d-ee839f5c7e3a)

**Comment by jbxenzxy** [comment]
it is ok in Microsoft Word but doesn't work in pdf.

**Comment by doug24** [comment]
This isn't unexpected, at least for me.  In Microsoft Word all of the words in a paragraph are one continuous flow, and the words wrap at the margins - there is no line break between `build` and `the`, just a single space. 

In order to search PDF, dnGrep extracts the text from the document (using pdftotext.exe) and searches the plain text.  In order to maintain the appearance of the PDF file, end of line characters are inserted in the text to make lines and paragraphs.  So now there are two characters between `build` and `the`, a carriage return and a line feed (\r\n).

To search for phrases crossing multiple lines, you need to tell dnGrep

**Comment by jbxenzxy** [comment]
I understand the difference between Word and PDF, I have a suggestion as follows:
When dnGrep search pdf files, it can add the \s+ between two characters by default, in order to hide the complicity for software users. Because users do not know whether the words wrap occur, where to occur.

**Comment by doug24** [comment]
I am extremely reluctant to write code that tries to anticipate the user's intent and modifies their query behind the scenes.  What if it isn't what they wanted, they don't know it happened, and they have no way to override it.  It may seem easy in this case, but I don't think it is good policy for the application.  

Once I get past the .NET 7 update, I'll review the current state of PDF libraries to see if anything is working better than what is being used now.

**Comment by doug24** [comment]
Just an update - I have been working on this using a third-party library - about 40 hours so far - but it's not ready for release yet.  Extracting text from PDF files is a very difficult problem, with academic papers going back many years. Adobe has 30 years of history in their code and anything I can put in dnGrep will not come close to their capability.  

There is no text in a PDF document - no words, sentences, lines, or paragraphs.  Just pages with printing instructions: letters at locations with font and color info, and vector or bitmap graphics.  Words are created by finding letters that are spatially close together.  But there are endless variations of layouts, spacing, ligatures, superscripts, hyphenation, duplicate overlapping letters, and graphic content that makes it near impossible to create searchable text for the general case. There will always be documents where the algorithms will fall down. Pdftotext.exe does a very admirable job.

**Comment by doug24** [comment]
In [v4.1.4](https://github.com/dnGrep/dnGrep/releases/tag/v4.1.4.0)
