### ISSUE TITLE
Update check detects 4.0.8 RC

### ISSUE THREAD

**Issue by JVimes** [dnGrep/dnGrep#871]
The update check detects v4.0.8 and leads to the 3.2.330 download page.

**Comment by doug24** [comment]
Hi John - 4.0.8 is a pre-release so GitHub doesn't mark it as the latest release.  And the code in dnGrep checking for new releases doesn't check if a release is a pre-release.  Hence the mismatch.  This doesn't happen often since this is the first pre-release I've done in years.  Could change the new version notification code to skip pre-releases.  I'm planning to do a new regular release (4.0.x) this week after Microsoft's patch Tuesday in case there is a new .NET 7.0.6 release.

**Comment by JVimes** [comment]
Thanks Doug! Might make the checker ignore pre-release. Not a huge deal of course. 🙂

**Comment by doug24** [comment]
Fixed in 4.0.26
