### ISSUE TITLE
request OCR to search in scanned PDF # enhancement

### ISSUE THREAD

**Issue by GXY2017** [dnGrep/dnGrep#888]
anyTXT searcher, the enhanced version includes OCR function to search the scanned PDF.  But it does not have any other advanced filters.

**Comment by doug24** [comment]
I'm going to pass on this request for a couple of reasons: First, I just don't have the time to spend on developing and maintaining a feature of this size.  Second, the most important feature of a search tool is to give accurate results, and I question whether this is possible with OCR given the range of languages, character sets, fonts, font sizes, and scan quality.  Would you be satisfied if the search did not find all documents or instances of something you searched for because the conversion to text was not 100%?

**Comment by GXY2017** [comment]
Thank you for your response.

1. I'm not sure about the technical difficulties. I apologize for this. As a common user, I have used Organize, the file manager, and its OCR implementation basically satisfies me.

2. Currently, I often use dnGREP and anyTxt searcher OCR version in combination. If the file name is a set of letters+ numbers, which are no longer understandable; or if the file name is named incorrectly, I often use OCR to search the file content. In addition, for scanned images saved as PDFs, I can also query them through keywords + file types (*.pdf).

Interestingly, when I suggested to anyTXT author to add the file name and file property search conditions, his response was similar to yours. He also didn't seem to think it was necessary to add a file name search function.

At least for now, I still need to use these two software in combination.
