### ISSUE TITLE
usability improvement: change selection on right click

### ISSUE THREAD

**Issue by Dromantor** [dnGrep/dnGrep#899]
It would be beneficial from my point of view if right click on a non-selected line in the result list also changes the selection to the right-clicked result before popping up the context menu. Currently you have to left click every item before issuing a right click, which gets annoying when I want to edit multiple files in a row.

Bonus improvement: Modifier key for opening a result file on double click, not just expanding it. Ctrl + double click or middle click alone would be nice. Currently you have to expand, then double click on a line, or right click -> open (which only works when first left clicking a line; see original request).

**Comment by doug24** [comment]
@Dromantor - thanks for the input. Yes, I think it will be easier if right click does the same selection changes as left click.

**Comment by doug24** [comment]
ctrl+double click isn't going to work because the first click with the ctrl key down changes the selection.  

I have alt+double click working, so thinking of going with that.

**Comment by doug24** [comment]
Handling the middle button click to open the file was easy but figuring out how to first change the selection on middle button click took a while.  I think we can keep both.

I think both middle click and alt+double click are both equally obscure, and I don't know a good in-app hint.  I'll put them in the help pages, but I doubt they see much traffic.

**Comment by doug24** [comment]
Both of these would be opening with the custom editor, if one is set in the options.  I wonder if one should open with the default application for the file association?  Same as "Open" and "Open with custom editor" on the context menu.

**Comment by Dromantor** [comment]
Didn't even think of this yet (and haven't seen "Open with custom editor" at all until now \*) as I don't have one configured.
One could add Alt+MCLK for that ;-) But then there is no modifer combination for doing the same with DBLCLK ...
Or just use the Alt+DBCLK for that, logic: it already has a modifier key in there, so this does something different than default, which is custom editor.
I start getting a headache the more I think about it ..... modifer key madness.

\* I noticed that a program restart is required for it to show the "Open with custom editor" in the context menu, or remove it again when removing the custom editor (which causes to open the default app when clicked after removing it). Wouldn't just greying it out (with tooltip: "Not configured.") be preferable? Improves discoverability.

For the discoverability of MK: MK is the first thing I tried after Ctrl+DBCLK and Shift+DBCLK didn't work. Since it has some comparable effects in other software (browser: open in new tab, windows taskbar: open new program instance, so something new opens in both cases), it may actually get some use without reading the help page.

**Comment by doug24** [comment]
Thanks for the suggestions on custom editor context menu.  I fixed the problem needing restart, made it visible always, disabled when no custom editor is configured, and added the "Not configured" tooltip.

Here's where I am with the actions:
Double click on a file node expands the node (existing functionality)
Double click on a child line opens in the custom editor if configured, otherwise the associated application (existing functionality).

Alt+double click on either a file node or child line opens in the associated application (new).

Middle mouse button click on either a file node or a child line opens in the custom editor if configured and the associated application otherwise (new).

I think this is the most uniform behavior given the existing double click action - the alt+double click does something different from plain double click.

**Comment by Dromantor** [comment]
Yeah, this sounds pretty good.

**Comment by doug24** [comment]
Added in [v4.0.69.0](https://github.com/dnGrep/dnGrep/releases/tag/v4.0.69.0)
