### ISSUE TITLE
Remove empty space from the UI

### ISSUE THREAD

**Issue by page200** [dnGrep/dnGrep#915]
For having a better overview of the search results, it's important to see much of them without having to scroll back and forth.

There's a lot of empty space in the UI. Some of it (space between different sections) can be kept for easy navigation, but much of it can be removed, so that there's more space for the search results below. Navigation will even improve if empty space is only where it should be rather than between everything. In the screenshot below, I've drawn rectangles around some empty space (and one of the two consecutive mentions of "dnGrep", and around "Byte", which currently goes on a separate line while there is still space for it in the previous line). Text fields seem too high (much higher than the characters inside them). I'll be happy to discuss how to visually group things (i.e. where to keep the space and where to remove it).

![image](https://github.com/dnGrep/dnGrep/assets/69221289/704b8321-a7ed-4b29-9ff3-f4f9cfdb890b)

**Comment by doug24** [comment]
I disagree, it is quite difficult to remove more space from the screen, which already extremely busy.  Two of the issues you show have to do with control wrapping because the window isn't wide enough - see more below.  But control wrapping is necessary for dynamic layout.  

There are a few things you need to consider:
1. dnGrep is currently translated into 17 different languages.  Most languages do not have the same length text as English.  The UI has to accommodate this with dynamic layout.
2. Not all screen sizes are the same, and not everyone wants the main window maximized or the same size.  The UI has to accommodate this with dynamic layout.
3. Some spaces are reserved for variable length messages, such as shown above "No symbolic links" which will grow with more hidden options selected.  There is another message area to the left of the star and plus bookmark buttons to show validation messages for Regular expressions, XPath and Byte search strings. The message areas are used to show important information without popping up dialogs.

To address your need for more space for the results, click the up arrow (expander) to the left of the "Search in results" checkbox.  This will expand the search results to nearly full window height.  dnGrep will do that automatically for you if you set the option "Maximize results panel on search" in the Options dialog under the "Search results" heading.  Click the button again to restore the filter panels to make changes before your next search.

To alleviate the vertical space needed by wrapping when there is insufficient horizontal space, you can hide any controls you don't use or rarely use. See the "Personalize control visibility" options under the "Layout" heading in the Options dialog, then check the "Personalize" menu under Setttings on the main menu. I never use XPath, Phonetic, or Byte searches, so I hide those options.  Same goes for Capture group search, Search in results, and Stop after first match.  That frees up enough space so the controls don't wrap onto a new line even when the main window is narrow, which gives me more room for the Preview window. If you need those hidden options you've hidden, just uncheck the Personalize menu item, and the full set will be restored.

Still not enough?  There is another option to move all the controls - Case sensitive, Whole word, Multiline, etc. - up into the expandable filters section and free up a line of vertical space. Use the "Show search options" radio buttons in the Layout section of the Options. 

<img src="https://github.com/dnGrep/dnGrep/assets/17227248/84d638cc-0a9b-45cc-9784-9488d4e6ad9d" width="400"/>

**Comment by page200** [comment]
> control wrapping is necessary for dynamic layout.

> * Most languages do not have the same length text as English.  The UI has to accommodate this with dynamic layout.

Dynamic layout is exactly the thing that _allows_ easily removing empty vertical space when languages are selected that don't need that space.

> * Not all screen sizes are the same, and not everyone wants the main window maximized or the same size.

That's the point. Some people don't have a huge screen, or have bad eyesight (require large text), and the empty vertical space makes them see super little of the search results. Even normal text size on a normal screen leaves little space for search results do to the large amount of emtpy space.

> The UI has to accommodate this with dynamic layout.

What does this have to do with empty vertical space?

> * Some spaces are reserved for variable length messages, such as shown above "No symbolic links" which will grow with more hidden options selected.

Okay, but surely not all ten empty spaces that I highlighted are reserved for that, right?

Maybe you misunderstood my message. Most of the empty spaces I highlighted don't sometimes contain text. Reducing them won't negatively affect anything.

> There is another message area to the left of the star and plus bookmark buttons to show validation messages for Regular expressions, XPath and Byte search strings.

Ah, that's why "Bytes" wraps, OK.

> To address your need for more space for the results, click the up arrow (expander) to the left of the "Search in results" checkbox. This will expand the search results to nearly full window height. 

> To alleviate the vertical space needed by wrapping when there is insufficient horizontal space, you can hide any controls you don't use or rarely use.

That forces me to switch back and forth between the several views. Suboptimal UI with the option to hide it is suboptimal UX!

Why not simply remove the empty vertical space (including too high text fields) that is not reserved for wrapping?

**Comment by doug24** [comment]
Have you tried to adjust the layout?

**Comment by doug24** [comment]
@page200 As you suggested, I adjusted the margins and padding, leaving the wrap panels as-is.  I didn't do anything with the Window title bar - moving the main menu there as was done in Visual Studio and VS Code may be possible since dnGrep already has a custom Window but that will be more work.  In total the top panels are 64.5 units smaller and that gives three more lines in the results. 

v4.069 is the window under my dev build on top. My font size is set to 14 because that's the way I always run it. I have personalization enabled to hide unused controls.  The window is narrower than normal for taking the screenshot, and the regular expression status message is clipped at this width.

<img src="https://github.com/dnGrep/dnGrep/assets/17227248/b69cf6d5-e8f2-49cc-aeaa-ac9641f41313" width="740"/>

**Comment by fade2gray** [comment]
Just a thought, couldn't `Regular expression is OK` be contracted to `Regex is OK`?
Also, just to square things up...
`Patterns to match:` => `Inclusion patterns:`, and `Patterns to exclude:` => `Exclusion patterns:`?

**Comment by doug24** [comment]
@fade2gray - Up until 2021 when I added the code to do translations, `Regular expression` was `Regex` everywhere, and I'm sure no one had a problem understanding the meaning. Then one of the translators insisted that the English strings be fixed before anyone could translate anything. He requested changing many - most - of the strings in the app.  Some were good suggestions to improve clarity and consistency, some I accepted with reservations, and some I refused to change.  Regex to Regular Expression was one I accepted to try to end the argument.

`Patterns to match` and `Patterns to exclude` have gone through a number of changes since I started working on the project in 2017.  I think these are good suggestions, but I don't think it is worth making the change.

Not that they can't be done, but making changes to the strings has become much more of an effort since the application has been translated.  Not so much for me, but for all the people who work on the translations.  If I changed the string back to Regex, and do it everywhere for consistency, then there are 18 strings changed in the translation dictionary, and the patterns phrases add 6 more.  When I commit those changes the translation tool (Weblate) reverts those 24 strings back to English in 17 different languages so they can be re-translated - even if there is no need to change the translation.  I'm pretty reluctant to do that to all the translators.

**Comment by fade2gray** [comment]
Fair do's.

**Comment by page200** [comment]
Thank you, the new screenshot looks much better! :)

I would also remove the vertical space between the text fields labeled "Search for" and "Replace with":
![image](https://github.com/dnGrep/dnGrep/assets/69221289/f7e6b938-004d-495d-aad7-70788d405788)


I'd also remove the groupboxes "Search in" and "Search" and instead draw just one line between those two groups of UI elements. ("Search" isn't a precise name anyway because it also contains "Replace with" and doesn't contain the contents of "Search in", which can be considered as part of "Search". Renaming "Search" to "Search & replace" wouldn't solve the latter problem. Renaming "Search" to "Search for" would conflict with the existing "Search for:" label.)

> When I commit those changes the translation tool (Weblate) reverts those 24 strings back to English in 17 different languages

The user of Weblate should be able to specify that the new string is a synonym of the old one and thus shouldn't revert other languages to English. Or more generally decide which languages not to revert. Would you like to report this as an issue to Weblate?

The term "regex" is unambiguous, and people who don't know it can look it up. On the other hand, some people know what "regular" means and what "expression" means, and might not realize that "regular expression" is an idiom and thus misunderstand it. Just saying in case the Weblate issue gets fixed for example :)

**Comment by doug24** [comment]
Fixed in v4.0.115
