### ISSUE TITLE
[feature] to add external previewer  for PDF instead "as text"

### ISSUE THREAD

**Issue by Aliaksandr3by** [dnGrep/dnGrep#945]
e.g.
"double click": with external viewer also is good working, but I think integrated work (portable version) is best
![image](https://github.com/dnGrep/dnGrep/assets/11432724/e32113ab-51f6-48ce-be56-b4c864b9446f)

![image](https://github.com/dnGrep/dnGrep/assets/11432724/ff9a794b-af17-4426-8c68-738e6de96338)

**Comment by doug24** [comment]
Yes, that would be nice, but it's probably not going to happen.  I'm not aware of any free components that could be embedded in dnGrep that allows the code to interact with the PDF data as text (words and lines).  In order to highlight the matching text, it needs to be bi-directional: convert the binary format to text for searching, then map the line number and character offset to a rectangular region in the document for highlighting. Maybe there is something out there, but I haven't seen it.  Most free PDF libraries I have tried have significant problems.   

What would be great is if Adobe changed their license to allow applications like dnGrep to use their software and provided Adobe Reader as a library or control with an API to interact with the document.

**Comment by Aliaksandr3by** [comment]
ok.  I understand.
thx
