### ISSUE TITLE
[request] open the full *.epub document

### ISSUE THREAD

**Issue by Aliaksandr3by** [dnGrep/dnGrep#950]
If I double click on epub searchings, to be opened only fragment of book

![image](https://github.com/dnGrep/dnGrep/assets/11432724/863e41cb-7707-4634-b98e-7bb37100d485)

**Comment by doug24** [comment]
@Aliaksandr3by - a couple of comments and questions:

dnGrep has two ways to open files in external applications: one uses the application associated with the file extension has you have defined in Windows, and the second is with the Custom editor that you can optionally configure in the dnGrep Options.

I think that opening the epub file as a whole will apply only to the application associated with the file extension, and not the custom editor. Or do you want to use the custom editor to open epub files too?

The other thing I want to note is that dnGrep does not know anything about the file format of epub files other than it is an archive. I do not have any way to map a matched string on a line in an html file inside an epub to a page and line number when the epub is viewed as a book. So dnGrep cannot do anything more that start the external application with the epub file and that application will open the book with its default behavior.

**Comment by Aliaksandr3by** [comment]
why if  I click on the searched segment of the book, I will open a segment of book in SumatraPDF ?
if I click the 'open' from the content menu, the EPUB is opend in FireFox (sd default bowser)
I have been using SumatraPDF for PDF/EPUB so on. 

![image](https://github.com/dnGrep/dnGrep/assets/11432724/7c606288-228a-4c01-88bb-de3af3eb8036)
![image](https://github.com/dnGrep/dnGrep/assets/11432724/6a0e7132-cc10-4544-bdf8-6536de9973b3)

![image](https://github.com/dnGrep/dnGrep/assets/11432724/da174e51-897f-4e3b-9faf-6fe6d0e3062b)

**Comment by doug24** [comment]
As I already said above, dnGrep doesn't know anything about epub file other than it is an archive file.  It does not open an application associated with .epub, just as it does not open an application associated with .zip or .rar, or any of the other archive file extensions.

The standard behavior for opening files contained in any archive is to extract the file from the archive and open the file.  That is what 99% of users want.

There are two ways to open a file: `Open` will open the file with the application associated with the file extension, and `Open with custom editor` will open the file with the editor you have defined in the Options - in your case, SumatraPDF.  

When you do `Open` on a match line, the inner **html** file will be extracted from the epub and opened in the application you have associated with html files - in your case, Firefox.

When you do `Open with custom editor` on a match line, the inner **html** file will be extracted from the epub and opened in your custom editor, SumatraPDF - but it is opening just the html file with the matching text, not the whole ebook.

This is completely expected - that is the way dnGrep has always handled files from any archive file type - it will only open files from within the archive, it will never open the entire archive.

Now, I have made a change for the next release where you can set an option to instruct dnGrep to open the whole archive using the application associated with the archive file extension.  So, if you have SumatraPDF associated with .epub, and you add epub to the new option, the doing an `Open` will open the whole book with SumatraPDF.  As far as I can tell, this is what you asked for in the original request.  When you open with the associated application, you cannot specify any additional command line arguments.

The question I was trying to get answered is do you also want the `Open with custom editor` to also open the epub as a file rather than extracting the file from the epub archive.  It seems the answer is yes.  

When using the custom editor, you can specify some additional command line arguments as you have shown, but most of them will not be useful.  %page is only valid for PDF files, %line and %column are relative to the inner html file. The -search "%match" works in SumatraPDF, but it only finds the first instance starting from the beginning of the book.

**Comment by doug24** [comment]
Added in [v4.0.129.0](https://github.com/dnGrep/dnGrep/releases/tag/v4.0.129.0)

**Comment by Aliaksandr3by** [comment]
it is don't work? or  maybe I don't understand how it is work?
if I click 'open' or 'open with custom editor' 
i will get firefox as a standart soft for  *.xhtml or file xhtml open with SumantraPdf
![image](https://github.com/dnGrep/dnGrep/assets/11432724/51cd1efa-6854-488b-996b-4874b189e173)
![image](https://github.com/dnGrep/dnGrep/assets/11432724/6fb26731-2a0f-45ed-872d-e0aae391f15b)

but I can click on explorer menu
![image](https://github.com/dnGrep/dnGrep/assets/11432724/6a4ff5ab-29fb-4868-86b6-28e9f231b00f)




![image](https://github.com/dnGrep/dnGrep/assets/11432724/41db48f6-7bae-460e-b4de-e590d97433ba)

**Comment by doug24** [comment]
This is an epub file you are trying to open, correct?  

Did you set this option in the Options dialog?

<img src="https://github.com/dnGrep/dnGrep/assets/17227248/eaff403d-7452-4fd9-aa38-718c6533520d" width="560"/>

**Comment by Aliaksandr3by** [comment]
nope, I don't use it.  sorry, it is my fault .



I think that the original '.\xpdf-tools-win\bin64\pdftotext.exe' work faster.
