### ISSUE TITLE
Feature request - details view and modify date 

### ISSUE THREAD

**Issue by alpha0x64** [dnGrep/dnGrep#954]
Hi, First of all your tool is awesome! I checked a lot of similar grep tools and yours has a lot features and looks really great. But still there is a room to add some useful features.

1. Please consider to add details view in bottom output window where we having output file names. There is a plenty white space ready to add some useful information about files, like file modification time, path, numer or findings etc. If this require to spend plenty of your time please just add some button (or tab) to change output view from "simple" to "details". BTW, you have dedicated "Sort" button there, but sorting by last modification time is terrible because require few additional clicks. This will be easier if we will have details view with option to click on column and sort files by that column. You can compare how output looks and works in the similar tool "grepWin". 

2. In Date (Modified/Created) section please consider to add some typical date ranges like: Modification in... last week / last year, etc. I often search some phrase in files that no older than 1 year.

As you see, I am mostly interested in modification time of files. In my daily routine scenario I often search some phrase in most recently files and checking the same result on 4-5 files from the top results. 
Thank you.

**Comment by doug24** [comment]
Thanks for your feedback. Yes, this has come up before. 
 
First, there is not plenty of white space for all users and all searches, it depends on your screen/app layout and what you are searching.  Searches in deep directory structures take a lot more space to show the path - and the path, filename, and match counts are probably the most important details to the most users.

The results list already shows the path and number of matches found. If you are not seeing those, please check the Options dialog in the 'Search results' section for the 'Show file path in the results panel' and 'Show additional details about the matches found'.  The file modification time is not shown in the results but is shown in the file tooltip (yet another option that can be enabled/disabled).

Why not have the results list show columns of data? Adding columns takes away fixed sizes of space in the results.  So, what happens when there isn't enough space? Does the file path and name get truncated or do the additional columns get scrolled off?  I have attempted this in the past and was never satisfied with the results. This is not a simple change: part of the problem is the horizontal scrolling depends on both the parent file lines and the child content lines. Second, the width of the file column depends on data not currently scrolled into the view, and the UI has to be fast and responsive for a large number of results. There's probably a solution, but I work on the project on my own time, and there simply isn't time to do everything.

Sorting the results takes only a single click to apply your preferred sort.  Just click the button and not the down arrow.  dnGrep remembers what you last set for sorting. Yes, it takes two clicks to change the sort if you are switching between two different sort options. I don't think this a hardship. Also note that most of the sort options do not readily apply to just clicking a column header, if the data was shown in columns.

Yes, 'typical' date ranges could be added but what's typical for all users? I don't want to add a lot of options just to cover all bases.  Do you frequently change between 1 week and 1 year?  You can set the calendar to a year, and you can set the past hours to 168 and switch between the two with one click.  Again, the dnGrep will remember your settings.
