### ISSUE TITLE
pdftotext returned 'Error opening PDF file' reading'FilePathAndName'

### ISSUE THREAD

**Issue by smoore-33** [dnGrep/dnGrep#956]
I just upgraded to the latest version of dngrep (Version 4.0.115.0) today and nearly all my PDFs now generate the above error. I believe I also noticed it on some PDFs with the prior version of dngrep I was running (4.0.45?). Many/most/all of the offending files were working with earlier versions of dngrep. I suspect that the offending files were created with an old version of Adobe Acrobat, probably version 9.
Is this a know issue?
If so, is there an expected fix?
I rely pretty heavily on dngrep. I'm tempted to go back to an earlier version of it, possibly 3.2.330. If I decide to do that, what version would you recommend? Would I need to do a complete uninstall before installing the older version?
Thanks.

**Comment by doug24** [comment]
I am not aware of a problem opening files and I have some pretty old test files.  In my test files, that is the error returned when a pdf file is password protected. Are your pdf files password protected, secured, or encrypted?

If you want help debugging this, you will have to upload a sample file for me to test.

Are you sure those files were actually opened and searched in earlier versions?  In 4.0.115 a change was made to report errors back to the results window, based on a request in issue #931. Previously these errors were only reported in the dnGrep error log, and you did not get an indication on screen that there was a problem opening the pdf file.

Pdftotext.exe was updated from 4.0.3 to 4.0.4 in dnGrep release 4.0.26 and hasn't been changed since.  If you want to go back to 4.0.3, you will need dnGrep 3.2.330. I would recommend getting the zip version of 3.2.330 from the releases page, unzip it to any local directory (not Program Files), and run it from that directory.  This way you can try the two versions side by side.  Make sure to check the logs/Grep_Error_Log.xml when running older versions.

If you use the msi installer for 3.2.330 or earlier versions, you will need to uninstall the current version of dnGrep. I would also recommend renaming the dnGrep.Settings.dat file because of settings file format changes.

You can run any version of pdftotext.exe with the latest version of dnGrep. If you find that 4.0.3 (or older) does work better for you, copy it from the 3.2.330 installation into the 4.0.115 installation.  Replace the pdftotext.exe in the dnGrep installation, check the command line arguments for the version you want to use and update them in the dnGrep Options dialog.

**Comment by smoore-33** [comment]
Thanks for your quick and very helpful reply. I’ll go through your suggestions as soon as I can get the time. The files aren’t password protected, secured, or encrypted. In fact, when I right-click within dnGrep and select Open, each of them opens just fine (without any password). I’m 98% sure that dnGrep is generating errors on files that earlier versions searched through successfully. I'm uploading a sample file that generates the error.
[form_ssa-7028_sample.pdf](https://github.com/dnGrep/dnGrep/files/12807120/form_ssa-7028_sample.pdf)

**Comment by doug24** [comment]
The error I get on this file is "Error related to PDF permissions".  I went back to pdftotext.exe 3.02, and I still get that same error.  Checking Adobe Acrobat Reader, there is security set on this document, and I suspect pdftotext is respecting those settings even though you can open it a reader and see the image.

But that is the bigger problem is this document: it is just an image, there are no fonts or characters in the pdf.  They only way possible to read this for searching is to use OCR, and dnGrep doesn't do OCR and probably never will.

![image](https://github.com/dnGrep/dnGrep/assets/17227248/6bc090cd-a655-431b-b5a5-6153f276d5c6)

**Comment by smoore-33** [comment]
'Sorry I didn't catch the fact that one of the files I provided couldn't be searched because it was an image. I'm providing two sample files. Sample1.pdf and Sample2.pdf. They're both contain readable text, but they are secured to prevent editing. They don't seem to be searchable. Does that mean that pdf's that have any kind of security applied can't be searched, even if reading is allowed? 

I'm not sure (yet) if this behavior is the same as or different from earlier releases. It may just be that I didn't notice it before because the access errors weren't being displayed, just logged in earlier versions.

Thanks again.

[Sample1.pdf](https://github.com/dnGrep/dnGrep/files/12923036/Sample1.pdf)
[Sample2.pdf](https://github.com/dnGrep/dnGrep/files/12923037/Sample2.pdf)

**Comment by doug24** [comment]
Below are the security properties as reported by Acrobat Reader using Menu -> Protection -> Security Properties.  The "Content Copying" and "Page Extraction" both prohibited by these documents.  Yes, you can view the files, but are not allowed to copy or extract text from them - that's what the document owner has set.

PDF documents do not have "text" as you expect to find it. There are no words, sentences, lines, or paragraphs in PDF files. They do have pages, and on each page are a collection of printer instructions: letters with a location, size, font, and color. By itself, a PDF document is unsearchable.  dnGrep uses a third-party application, 'pdftotext.exe' to extract text from PDF documents into a plain text file, then dnGrep searches the plain text.  Running pdftotext from the command line returns "Permission Error: Copying of text from this document is not allowed" for versions 3 and 4 of pdftotext, so dnGrep has never been able to extract text from these files.  I haven't done testing to see what security properties pdftotext uses, but I suspect it would include either Content Copying and Page Extraction, and possibly others.

The difference in v4.0.115 of dnGrep is that you are now seeing these errors in the results list where previous version of dnGrep only wrote the errors to the log file and silently ignored them in the results list - as if the file never existed. I was not aware of this issue or the security flags in PDF files until a user brought this up in another bug report. I had to go find some PDF files with security enabled to add to my set of test files.

Adobe Acrobat Reader, XPDFReader, Google Chrome, and Microsoft Edge all respect the permission flags, and you cannot copy or extract text from these files. It is possible to find other PDF tools that ignore the permissions.

Sample1.pdf
<img src="https://github.com/dnGrep/dnGrep/assets/17227248/4d157515-bbc3-4d94-8058-89559ef2db54" width="400"/>

Sample2.pdf
<img src="https://github.com/dnGrep/dnGrep/assets/17227248/c2375ac5-676d-4d2c-b8c1-0e6664b9ffbe" width="400"/>
