### ISSUE TITLE
dngrep portable adds wrong reference for right click context menu in windows 10

### ISSUE THREAD

**Issue by xfilesee34** [dnGrep/dnGrep#958]
The added key to registry refers to dngrep.dll maybe it should refer to dngrep.exe?

**Comment by doug24** [comment]
Thanks for the report - yes, I missed that. The exe and dll file generation changed in .NET 7 - code that was in dnGrep.exe is now in dnGrep.dll. The code generating the registry entries looks up the assembly name to find the location on disk and is now getting the wrong assembly.  Will be fixed in the next release (next week).

**Comment by doug24** [comment]
Fixed in [v4.0.129.0](https://github.com/dnGrep/dnGrep/releases/tag/v4.0.129.0)
