### ISSUE TITLE
[feature] PREV and NEXT button to traverse the search results

### ISSUE THREAD

**Issue by xfilesee34** [dnGrep/dnGrep#968]
I think currently that can be done using F3 and F4, but there can be buttons either under the search bar or next to pop out window button in the preview pane.

**Comment by doug24** [comment]
I'll think about this but am not sold on the idea.  You can use the function keys and you can navigate with the mouse (but yes, it takes more than one click).

The problem is space and an already cluttered user interface.  The area next to the pop out window button has two problems: it's on an optional part of the UI (needs show preview) and the area is used for the file path and name. Already have had complaints that the file path and name is truncated and adding buttons will only make it worse.  

The area below the search bar will mean adding an additional row of buttons which will shrink the results pane.  Already have had lots of complaints that the search area takes too much space and there is not enough room for the results.

**Comment by Aliaksandr3by** [comment]
might it split screen give better result?
![image](https://github.com/dnGrep/dnGrep/assets/11432724/761e2d4c-a28e-4da0-aa7c-68c24c36e908)

**Comment by doug24** [comment]
Added in [v4.0.189](https://github.com/dnGrep/dnGrep/releases/tag/v4.0.189.0)
